cecho("<CadetBlue>Welcome to the <green>Sunder <DeepSkyBlue>bashing<CadetBlue> help file!")
cecho("\n<MediumSeaGreen>------------------------------------------")
cecho("\n<green>Sunder <ForestGreen>has several methods of helping you bash, from hitting things in your room to helping you navigate the landscape of Aetolia and its many areas. You can easily know if <green>Sunder<ForestGreen> recognizes your area by doing a check with the <red>SURVEY<ForestGreen> command. As long as you see mob names, <green>Sunder<ForestGreen> will be able to hit things for you.")
cecho("\n")
cecho("\n<red>Consider this your warning: <ForestGreen>The folks who upkeep Sunder do not, by any means, condone or suggest using Sunder to do things while you are AFK or otherwise unable to attend to your character. From HELP AUTOMATION -> FULLY automating quests and hunting - with movement and all actions included in the triggers - are allowed so long as one is present at the computer, as well as gambling automation. Please do not abuse what is being given to you without regard for the admin stance.")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<DeepSkyBlue>aa                    <ForestGreen>Make <green>Sunder <ForestGreen>try to hit everything in the room!")
cecho("\n                     <ForestGreen> If there is nothing left in the room, this will turn off.")
cecho("\n<DeepSkyBlue>ff                    <ForestGreen>Want to walk around manually and have Sunder hit things? Use this.")
cecho("\n                     <ForestGreen> It automatically turns on hitting when it finds a valid target.")
cecho("\n<DeepSkyBlue>fba <leader>          <ForestGreen>Will start attacking when the leader attacks. Good for duobashing.")
cecho("\n                     <ForestGreen> NOTE: Does not auto-sync targets. Will be like you entered aa yourself.")
cecho("\n<DeepSkyBlue>grp <person>          <ForestGreen>Inform <green>Sunder<ForestGreen> of your bashing party.")
cecho("\n<DeepSkyBlue>grp queen rook pawn   <ForestGreen>Example of adding more than one person.")
cecho("\n<DeepSkyBlue>orbs                  <ForestGreen>Activate your ylem orbs with one alias!")
cecho("\n<DeepSkyBlue>buyorbs               <ForestGreen>Buy the four good orbs at once. White orb is lame.")
cecho("\n<DeepSkyBlue>toggle generic <ForestGreen>Use generic mob type instead of number to bash.")
cecho("\n")
cecho("\n")
cecho("\n<green>Sunder<ForestGreen> has some more advanced features listed in <DeepSkyBlue>sunder help autobashing<ForestGreen>.")


cecho("\n<MediumSeaGreen>------------------------------------------")