cecho("<CadetBlue>Welcome to the <green>Sunder <DeepSkyBlue>autobashing<CadetBlue> help file!")
cecho("\n<MediumSeaGreen>------------------------------------------")
cecho("\n<green>Sunder <ForestGreen>recognizes a good majority of the areas in the game, including the main bashing areas and most of the ones you might use while gaining levels. The following methods will help you bash these areas, either singular or multiple at a time.")
cecho("\n")
cecho("\n<red>Consider this your warning: <ForestGreen>The folks who upkeep Sunder do not, by any means, condone or suggest using Sunder to do things while you are AFK or otherwise unable to attend to your character. From <red>HELP AUTOMATION -><ForestGreen> 'FULLY automating quests and hunting - with movement and all actions included in the triggers - are allowed so long as one is present at the computer, as well as gambling automation.' <red>Please do not abuse what is being given to you without regard for the admin stance.")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<DeepSkyBlue>goarea               <ForestGreen>Bash the current area you're in and then walk back to your city.")
cecho("\n                     <ForestGreen>Use this for bashing just one area. No need to use the below command.")
cecho("\n")
cecho("\n<DeepSkyBlue>bashpath <areas>     <ForestGreen>Define your custom bashing route from valid areas.")
cecho("\n                     <ForestGreen>It will automatically walk you from the last room of area 1 to area 2, etc.")
cecho("\n")
cecho("\n<DeepSkyBlue>bashpath tiyen, xaanhal, mamashi <ForestGreen>- for example, would bash those areas and then head home.")
cecho("\n")
cecho("\n<ForestGreen>There are some more functions in the scripts for use in your code for creating paths, doing new areas, etc.")
--You would want to look into SND Autopaths->Creating->start/add/compile.


cecho("\n<MediumSeaGreen>------------------------------------------")