cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>FISHING <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>------------------------------------------")
cecho("\n<ForestGreen>Our <green>Sunder <ForestGreen>fishing system has been put together from several different systems, and will help you with your fishing milestones or just when you want to kick back and relax to earn some gold. The first thing you will want to do is set the amount of max fish you want to catch using <DeepSkyBlue>sunder maxfish # <ForestGreen>and the amount of fish currently in your bucket using <DeepSkyBlue>sunder fishbucket #<ForestGreen>. Once this is done just turn on the autofisher and let <green>Sunder <ForestGreen>do the rest. You will notice that all the spam has been removed, but it is still working and will notify you when it turns off due to reaching the maxfish amount or if the fishing hole is empty.")
cecho("\n")
cecho("\n<red>Consider this your warning: <ForestGreen>The folks who upkeep Sunder do not, by any means, condone or suggest using Sunder to do things while you are AFK or otherwise unable to attend to your character. From HELP AUTOMATION -> FULLY automating quests and hunting - with movement and all actions included in the triggers - are allowed so long as one is present at the computer, as well as gambling automation. Please do not abuse what is being given to you without regard for the admin stance.")
cecho("\n")
cecho("\n<CadetBlue>HOW IT WORKS!")
cecho("\n<MediumSeaGreen>-------------")
cecho("\n<ForestGreen>1. Put up your wielded items manually and wield your pole.\n")
cecho("<ForestGreen>2. Go to a fishing hole.\n")
cecho("<ForestGreen>3. Do '<DeepSkyBlue>FISHING DISCERN<ForestGreen>' to make sure you see fish. This will\n")
cecho("<ForestGreen>   track the hole type, vnum, and what fish you see automatically\n")
cecho("<ForestGreen>   in a database it creates on the first time you use it.\n")
cecho("<ForestGreen>4. If you can fish there and there are fish, type in '<DeepSkyBlue>afish<ForestGreen>'\n") 
cecho("<ForestGreen>   to turn on the auto-fisher.\n")
cecho("<ForestGreen>5. If you run out of fish in this hole, it will turn off fishing on\n")
cecho("<ForestGreen>   its own. You can also type in '<DeepSkyBlue>afish<ForestGreen>' to turn it off.\n")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>afish                       <ForestGreen> Turns the auto-fisher off/on")
cecho("\n<DeepSkyBlue>sunder maxfish <amount>  <ForestGreen>    Set and check the max amount of fish you want to catch.")
cecho("\n<DeepSkyBlue>sunder fishbucket <amount> <ForestGreen>  Set and check the amount of fish in your bucket.\n                             Using <DeepSkyBlue>sunder fishbucket clear <ForestGreen>will set the amount to '<green>0<ForestGreen>'")
cecho("\n<DeepSkyBlue>fishing search ??        <ForestGreen>    You can search for a water hole type, or fish, from holes you've\n                             discerned.")
cecho("\n<DeepSkyBlue>fishing search full ??       <ForestGreen>If you prepend <DeepSkyBlue>info<ForestGreen> or <DeepSkyBlue>full<ForestGreen> it displays complete info instead of\n                             abridged.")
cecho("\n<DeepSkyBlue>fgo ?? <ForestGreen>                      Search and path to a specific fishing hole. EX: <DeepSkyBlue>fgo vortex<ForestGreen>.")
cecho("\n<MediumSeaGreen>------------------------------------------")