cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>FLUIDCACHE <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>---------------------------------------------")
cecho("\n<ForestGreen>Ever log in and notice you lost a bunch of refills because your vials, bandages, or (gods forbid) rags decayed? Well NO MORE! Or at least, LESS LIKELY! <green>Sunder <ForestGreen>is now equipped with a few more aliases to help alleviate this problem!")
cecho("\n")
cecho("\n<CadetBlue>HOW IT WORKS!")
cecho("\n<MediumSeaGreen>-------------")
cecho("\n<ForestGreen>Simply input the alias you want to use and then either let <green>Sunder <ForestGreen>fill your empty vials, bandages, or rags or consume them into your fluidcache. If you are new to Aetolia, make sure you read <green>HELP FLUIDCACHE <ForestGreen>if you have not already!")
cecho("\n")
cecho("\n<ForestGreen>Keep in mind that these aliases will not buy anything for you. Please refer to <DeepSkyBlue>sunder help shops <ForestGreen>to see the aliases that will purchase bulk items for you!")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>venoms                <ForestGreen>First buy the rags you need for combat and type <DeepSkyBlue>venoms")
cecho("\n                      <ForestGreen>to have <green>Sunder <ForestGreen>fill your rags for you. You can search this")
cecho("\n                      <ForestGreen>alias in your scripts to change which venoms you want it to fill!")
cecho("\n")
cecho("\n<DeepSkyBlue>unvenom               <ForestGreen>Just what it says! Typing <DeepSkyBlue>unvenom <ForestGreen>will fluidcache consume")
cecho("\n                      <ForestGreen>all the venoms from your rags!")
cecho("\n")
cecho("\n<DeepSkyBlue>fillvials             <ForestGreen>This alias will fill the vials in your inventory from your fluidcache.")
cecho("\n")
cecho("\n<DeepSkyBlue>unfillvials           <ForestGreen>Like <DeepSkyBlue>unvenom<ForestGreen>, this alias will consume the elixirs")
cecho("\n                      <ForestGreen>in your vials back into your fluidcache.")
cecho("\n")
cecho("\n<DeepSkyBlue>fillbandages          <ForestGreen>This will fill the clean bandages in your inventory with the poultices")
cecho("\n                      <ForestGreen>from your fluidcache.")
cecho("\n")
cecho("\n<DeepSkyBlue>unfillbandages        <ForestGreen>Again... same as the other 'un' aliases, but for poultices.")
cecho("\n<MediumSeaGreen>---------------------------------------------")