cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>Name Database <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>-------------------------------------------")
cecho("\n<ForestGreen>The name databse that <green>Sunder<ForestGreen> utilizes will be familiar to many of you who have come from other IRE games, including the utilization and coloring effects. See below for aliases to toggle certain items and general upkeep of the names contained.")
cecho("\n")
cecho("\n<ForestGreen>Please note that you do NOT need to utilize the highlighting if you do not want to, but you absolutely do need the name database for other functions of <green>Sunder<ForestGreen>.")
cecho("\n")
cecho("\n<CadetBlue>HOW IT WORKS!")
cecho("\n<MediumSeaGreen>------------")
cecho("\n<ForestGreen>By default, the name database should be installed when you set everything up.")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>pb help                <ForestGreen>Pull up the help file for the phone book.")
cecho("\n<DeepSkyBlue>pb settings            <ForestGreen>Shows you current color configuration of everyone.")
cecho("\n<DeepSkyBlue>pb hl                  <ForestGreen>Toggles the highlighting of names on/off.")
cecho("\n<DeepSkyBlue>pb hl <org> <color>    <ForestGreen>Change your custom color config per city.")
cecho("\n<DeepSkyBlue>pbu                    <ForestGreen>Update and honor people from qw/qwho.")
cecho("\n<DeepSkyBlue>pb set <person> <city> <ForestGreen>Set someone's city manually.")
cecho("\n<DeepSkyBlue>pb remove <person>     <ForestGreen>Remove a person from the phonebook.")
cecho("\n<DeepSkyBlue>pbh <person>           <ForestGreen>Update one individual person.")
cecho("\n<DeepSkyBlue>cw/cwho                <ForestGreen>Record everyone currently online from your city.")
cecho("\n<DeepSkyBlue>qws                    <ForestGreen>Displays a qw list, sorted by city.")
cecho("\n<DeepSkyBlue>pb enable              <ForestGreen>Turn on highlighting.")
cecho("\n<DeepSkyBlue>pb disable             <ForestGreen>Turn off highlighting.")
cecho("\n")
cecho("\n<ForestGreen>There are some more functions in the scripts for use in your code for checking city if they exist in the database etc.")
cecho("\n")
cecho("\n<MediumSeaGreen>-------------------------------------------")