cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>QUESTING <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>-------------------------------------------")
cecho("\n<ForestGreen>Always ending up with odds and ends in your inventory or kestrels following you around EVERYWHERE because you dared to walk through Three Widows? Well no more! You will now be able to toggle quests on and off so that you only whistle or pick up items when you want!")
cecho("\n")
cecho("\n<CadetBlue>HOW IT WORKS!")
cecho("\n<MediumSeaGreen>------------")
cecho("\n<ForestGreen>As of right now, there is only one toggle to turn it on/off. More may be added in the future! It will not auto-walk areas for you, you will still need to walk around and while you do so <green>Sunder<ForestGreen> will pick up items and turn them in as appropriate. ")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>toggle questing       <ForestGreen>Toggles questing on/off")
cecho("\n<MediumSeaGreen>-------------------------------------------")