cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>SHOPS <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>----------------------------------------")
cecho("\n<ForestGreen>Purchasing necessary items from shops can be a bit mundane, but NO MORE! Often you will find yourself buying many refills or masses of pills - to help combat this, <green>Sunder <ForestGreen>includes a few aliases to help make that less painful!")
cecho("\n")
cecho("\n<CadetBlue>HOW IT WORKS!")
cecho("\n<MediumSeaGreen>-------------")
cecho("\n<ForestGreen>The first thing you need to do is find a shop. You can do this by going to any city (including Esterport!) and using <DeepSkyBlue>PATH TRACK DIRECTORY<ForestGreen>. This will take you to the directory where you can peruse all the shops in that city (think of it like a search engine). From there you can <DeepSkyBlue>DIRECTORY <ForestGreen>'<DeepSkyBlue>item<ForestGreen>' to see which shop is carrying the item(s) you need. If you have MXP turned on, you can click on the vnum for the shop you want or <DeepSkyBlue>PATH TRACK vnum <ForestGreen>to get there.")
cecho("\n")
cecho("\n<ForestGreen>Once you are in a shop, you will simply need to put in the alias for the items you wish to purchase and let <green>Sunder <ForestGreen>do the rest!")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>buypills #            <ForestGreen>Pills! Typing <DeepSkyBlue>buypills <ForestGreen>followed by an amount will buy that amount")
cecho("\n                      <ForestGreen>of every type of pill! EXAMPLE: <DeepSkyBlue>buypills 500 <ForestGreen>will buy <LimeGreen>500 <ForestGreen>of each pill.")
cecho("\n")
cecho("\n<DeepSkyBlue>fillcache # type      <ForestGreen>Fluidcache! Just use <DeepSkyBlue>fillcache <ForestGreen>followed by the number of times")
cecho("\n                      <ForestGreen>you want to buy a refill and what type of refill you want to buy.")
cecho("\n                      <ForestGreen>The types are: <DeepSkyBlue>venoms<ForestGreen>, <DeepSkyBlue>poultices<ForestGreen>, and <DeepSkyBlue>elixirs<ForestGreen>. EXAMPLE: <DeepSkyBlue>fillcache") 
cecho("\n                      <DeepSkyBlue>10 elixirs <ForestGreen>will purchase <LimeGreen>10 <ForestGreen>refills of each type of elixir. The purchase")
cecho("\n                      <ForestGreen>line may be gagged, so just check your FC before and after purchasing!")
cecho("\n                      <LimeGreen>**NOTE** <ForestGreen>This will buy the amount of refills, so to fill your cache(<LimeGreen>1500<ForestGreen>)")
cecho("\n                      <ForestGreen>you will only need to purchase <LimeGreen>30 <ForestGreen>refills!")
cecho("\n<MediumSeaGreen>----------------------------------------")