cecho("<CadetBlue>Welcome to the <green>Sunder <DeepSkyBlue>UTILITIES <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>------------------------------------------")
cecho("\n<green>Sunder <ForestGreen>has several different utilities that are quite useful! Below is a summarized list that will direct you to the correct files so that you can become familiar with them and reference back to them at any time!")
cecho("\n")
cecho("\n<MediumTurquoise>To view the following <green>Sunder <MediumTurquoise>help files, use <DeepSkyBlue>sunder help <MediumTurquoise><filename>!")
cecho("\n<DeepSkyBlue>Vermin               <ForestGreen>Explantion on <green>Sunder's <ForestGreen>vermin autobasher!")
cecho("\n<DeepSkyBlue>Fishing              <ForestGreen>Explantion on how to use <green>Sunder's <ForestGreen>fishing utilities!")
cecho("\n<DeepSkyBlue>Shops                <ForestGreen>Quick aliases to make purchasing easier!")
cecho("\n<DeepSkyBlue>Fluidcache           <ForestGreen>Aliases to consume and fill vials/rags/bandages!")
cecho("\n<DeepSkyBlue>Who                  <green>Sunder's <ForestGreen>WHO parsing system and how it works!")
cecho("\n<DeepSkyBlue>Questing             <ForestGreen>Helpful questing aliases (no more pesky kestrels following you around!)")
cecho("\n<DeepSkyBlue>PB                   <ForestGreen>All the commands for the name databse.")
cecho("\n<DeepSkyBlue>find my profile      <ForestGreen>Locate the directory for your profile.")
cecho("\n")
cecho("\n<MediumSeaGreen>------------------------------------------")