cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>VERMIN <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>-----------------------------------------")
cecho("\n<ForestGreen>We get it! Every time you see that daily/weekly/monthly(especially the monthly) milestone for vermin, you just want to run head first into a team of mages collapsing singularities and calamaties! So hopefully these will make your life easier from here on out and save you from death by mages! No guarantees :(")
cecho("\n")
cecho("\n<CadetBlue>HOW IT WORKS!")
cecho("\n<MediumSeaGreen>-------------")
cecho("\n<ForestGreen>First, you will want to make sure you are wielding whatever you need to kill the vermin. After you are ready to start your quest of ridding a city of its vermin, you just <DeepSkyBlue>PATH TRACK <ForestGreen>to any city <LimeGreen>(make sure you are not an enemy!) <ForestGreen>and then type <DeepSkyBlue>toggle vermin <ForestGreen>to start! This will work similar to <DeepSkyBlue>gogo <ForestGreen>in that it will just begin bashing from where you are currently. No matter which city you begin your vermin bashing in, it will end at the vermin mob and will automatically sell your vermin! So no more accidental offerings of vermin to your gods! Should you need to finish early, just type <DeepSkyBlue>toggle vermin <ForestGreen>again and an echo will pop up to remind you to go sell your vermin!")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>toggle vermin         <ForestGreen>Toggles the vermin autobasher on/off")
cecho("\n<MediumSeaGreen>-----------------------------------------")