cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>WHO <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>---------------------------------------")
cecho("\n<ForestGreen>Tired of looking through the who list trying to figure out who is where and who they are with when looking for that pesky lesser that was just tapped? Well, thanks to <green>Czcibor<ForestGreen>, <green>Sunder <ForestGreen>has built in group checking via the who list!")
cecho("\n")
cecho("\n<CadetBlue>HOW IT WORKS!")
cecho("\n<MediumSeaGreen>-------------")
cecho("\n<ForestGreen>Using the alias <DeepSkyBlue>WHO GROUPS <green>Sunder <ForestGreen>will now sift through the who list and capture room locations. Once it is done with that, it will show you the names of the rooms that have more than one person in that location, how many people are there, and then who all is in that location! Note that those with the <red>cloaking<ForestGreen> artifact or in hidden rooms are unable to be tracked in this manner.")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>who groups            <ForestGreen>Shows the full WHO list and then the grouped rooms with more than one person")
cecho("\n<MediumSeaGreen>---------------------------------------")