if not npb.help_handled then
  cecho("\n-----------------------------INFORMATION ------------------------------")
  cecho("\n Phone Book (ndb replacement) help")
  cecho("\n pb is meant to provide a more reliant solution to knowing who belongs ")
  cecho("\n to which city and highlighting it.\n")
  cecho("\n Below currently supported commands. Each command also has a shorthand.")
  cecho("\n <b>Note<reset>: NPB is very very new and thus will contain bugs.")
  cecho("\n Please let Nerissa know if you find one.")
  cecho("\n------------------------------ COMMANDS -------------------------------")
  cecho("\npb help - this helpfile")
  cecho("\npb update/pbu - update and honour people from qwho")
  cecho("\npb honour/pbh - update a specific persons city from their honours.")
  cecho("\ncwho - record everone currently online from your city")
  -- cecho("\npb enable - turn on highlighting")
  -- cecho("\npb disable - turn off highlighting")
  cecho("\npb set <person> <city> - set someone's city manually")
  cecho("\npb hl|toggle highlights - toggle city highlighting")
  cecho("\npb settings - Show highlighting settings")
  cecho("\npb hl <city> <color> - change city highlighting")
  cecho("\npb remove <person> - remove a person from the phonebook")
  cecho("\nqws - Show online people, sorted by city")
  cecho("\n-----------------------------------------------------------------------")
end
npb.help_handled = false