--Nested tables incase someone wants to add a devil y/n field to cards and change picking based on it, though so few use it that it may not come to fruition.
snd.cardshapes =
{
  indorani =
  {
    stupidity = { card = "moon" },
    confusion = { card = "moon" },
    epilepsy = { card = "moon" },
    anorexia = { card = "moon" },
    berserking = { card = "moon" },
    weariness = { card = "moon" },
    impatience = { card = "moon" },
    recklessness = { card = "moon" },
    perplexed = { card = "sun" },
    asthma = { card = "sun" },
    clumsiness = { card = "sun" },
    vomiting = { card = "sun" },
    lethargy = { card = "sun" },
    sensitivity = { card = "sun" },
    hearing = { card = "sun" },
    hypersomnia = { card = "sun" },
    migraine = { card = "sun" },
    superstition = { card = "sun" },
    prone = { card = "hangedman" },
    writhe_ropes = { card = "hangedman" },
    justice = { card = "justice" },
    lovers_effect = { card = "lovers" },
    wheel = { card = "wheel" },
    slickness = { card = "adder" },
    haemophilia = { card = "adder" },
    aeon = { card = "aeon" },
    shyness = { card = "adder" },
    allergies = { card = "adder" },
    peace = { card = "adder" },
    paresis = { card = "adder" },
    slickness = { card = "adder" },
    stuttering = { card = "adder" },
    blurry_vision = { card = "adder" },
    deadening = { card = "adder" },
    disfigurement = { card = "adder" },
    squelched = { card = "adder" },
    left_arm_crippled = { card = "adder" },
    right_arm_crippled = { card = "adder" },
    left_leg_crippled = { card = "adder" },
    right_leg_crippled = { card = "adder" },
  },
  oneiromancer =
  {
    stupidity = { card = "hypercube" },
    confusion = { card = "hypercube" },
    epilepsy = { card = "hypercube" },
    anorexia = { card = "hypercube" },
    berserking = { card = "hypercube" },
    weariness = { card = "hypercube" },
    impatience = { card = "hypercube" },
    recklessness = { card = "hypercube" },
    perplexed = { card = "sphere" },
    asthma = { card = "sphere" },
    clumsiness = { card = "sphere" },
    vomiting = { card = "sphere" },
    lethargy = { card = "sphere" },
    sensitivity = { card = "sphere" },
    hearing = { card = "sphere" },
    hypersomnia = { card = "sphere" },
    migraine = { card = "sphere" },
    superstition = { card = "sphere" },
    prone = { card = "wreath" },
    writhe_ropes = { card = "wreath" },
    justice = { card = "knight" },
    lovers_effect = { card = "heart" },
    wheel = { card = "cardinal" },
    slickness = { card = "diamond" },
    haemophilia = { card = "diamond" },
    aeon = { card = "hourglass" },
    despair = { card = "phantasmagoria" },
    shyness = { card = "diamond" },
    allergies = { card = "diamond" },
    peace = { card = "diamond" },
    paresis = { card = "diamond" },
    slickness = { card = "diamond" },
    stuttering = { card = "diamond" },
    blurry_vision = { card = "diamond" },
    deadening = { card = "diamond" },
    disfigurement = { card = "diamond" },
    squelched = { card = "diamond" },
    left_arm_crippled = { card = "diamond" },
    right_arm_crippled = { card = "diamond" },
    left_leg_crippled = { card = "diamond" },
    right_leg_crippled = { card = "diamond" },
  },
}
