snd.def_options = {

  none = {

  },

  general_defs = {
    def_thirdeye = "on",
    def_mindseye = "once",
    def_cloak_tattoo = "on",
    def_kola = "on",
    def_deathsight = "on",
    def_insomnia = "on",
    def_arcane = "on",
    --def_frost = "on",
    --def_venom = "on",
    def_levitation = "on",
    def_speed = "on",
    --def_caloric = "on",
    def_nightsight = "on",
    def_clarity = "once",
  },

  akkari = {
    def_ardour_constitution = "once",
    def_relentless = "on",
    def_resolved = "on",
    def_celerity = "on",
    def_acuity = "on",
    def_stalking = "once",
    def_suppressed = "once",
    def_retaliation = "once",
    def_ascetic = "on",
    def_holylight = "once",
  },


  alchemist = {
    def_interposition = "on",
    def_obfuscation = "on",
    def_cognisance = "once",
    def_resuscitation = "on",
    def_conduit_crutch = "on",

  },

  archivist = {
    def_irongrip = "once",
    def_spheres = "once",
    def_linked = "once",
    def_oneness = "once",
    def_sublimation = "once",
    def_ameliorate = "once",
    def_catabolism = "once",
  },

  ascendril = {
    def_countercurrent = "on",
    def_empowered_boar = "once",
    def_arcaneskin = "on",
  },

  bard = {
    def_sheath = "once",
    def_charisma = "on",
    def_euphonia = "once",
    def_aurora = "once",
  },

  bear = {
    def_weathering = "on",
    def_bodyheat = "once",
    def_metabolism = "once",
    def_celerity = "once",
    def_thickhide = "once",
    def_bracing = "once",
    def_harden = "once",
  },

  bloodborn = {
    def_panoply = "on",
    def_empowered_boar = "once",
    def_forestall = "on",
  },

  carnifex = {
    def_fearless = "on",
    def_reveling = "once",
    def_recklessness = "once",
    def_soulharvest = "on",
    def_soulthirst = "on",
    def_soul_fortify = "on",
    def_soul_fracture = "once",
    def_irongrip = "once",
    --def_herculeanrage = "once",
    def_cruelty = "on",
  },

  earthcaller = {
    def_heatshield = "once",
    def_battlehymn = "once",
    def_smothering = "once",
    def_constitution = "once",
    def_insulation = "once",
    def_unbending = "once",
  },

  indorani = {
    def_irongrip = "once",
    def_deathaura = "once",
    def_lifevision = "on",
    def_soulmask = "on",
    def_gravechill = "on",
    def_vengeance = "on",
    def_soulcage = "on",
    def_shroud = "on",
    def_hierophant = "once",
    def_chariot = "on",
    def_eclipse = "on",
    -- def_devilpact = "on",
    def_soulcage = "on",
    def_morisensus = "once",
  },

  luminary = {
    def_lightshield = "once",
    def_inspiration = "once",
    def_fireblock = "once",
    def_constitution = "once",
    def_insulation = "once",
    def_boilingblood = "once",
  },

  monk = {
    def_weathering = "on",
    def_toughness = "on",
    def_vitality = "on",
    def_regeneration = "on",
    def_resistance = "on",
    def_constitution = "on",
    def_split_mind = "on",
    def_kaido_immunity = "on",
    def_boosted_regen = "on",
    def_consciousness = "on",
  },

  oneiromancer = {
    def_irongrip = "once",
    def_intoxication = "once",
    def_lifevision = "on",
    def_redoubt = "on",
    def_glaciation = "on",
    def_defiance = "on",
    def_remembrance = "on",
    def_shroud = "on",
    def_fan = "once",
    def_crane = "on",
    def_cloud = "on",
    def_tapestry = "once",
    --def_faerie = "on",
  },

  praenomen = {
    def_potence_constitution = "once",
    def_fortify = "on",
    def_corpus_warding = "on",
    def_celerity = "once",
    def_lifescent = "once",
    def_lifevision = "once",
    -- def_veil = "on",
    def_stalking = "once",
    def_concentrate = "on",
    def_shadowblow = "on",
    def_blurred = "once",
    def_elusion = "once",
    def_trepidation = "once",
    -- def_deathlink = "on",
  },

  ravager = {
    def_vinculum = "on",
    def_ruthlessness = "on",
    def_impenetrable = "on",
    def_criticality = "on",
    def_unfinished = "on",
    def_exhilarate = "on",
    def_reflexes = "on",
    def_contempt = "once",
    def_velocity = "on",
    def_untouchable = "on",
    def_inflated = "on",
  },

  revenant = {
    def_gripping = "once",
    def_maingauche = "once",
  },

  runecarver = {
    def_prowess          = "once",
    def_hex_stalk        = "once",
    def_hex_preservation = "once",
    def_ironbark         = "once",
    def_empowered_moon   = "once",
    def_rot_carpet       = "once",
  },

  sciomancer = {
    def_rigor          = "on",
    def_shadow_engulf  = "once",
    def_shadow_mantle  = "on",
    def_blurring       = "on",
    def_empowered_moon = "on",
    def_featherstep    = "once",
  },

  sentinel = {
    def_irongrip = "once",
    def_lifesap = "on",
    def_barkskin = "on",
    def_hardiness = "on",
    def_conceal = "once",
    def_maskedscent = "once",
    def_vitality = "on",
    def_flexibility = "once",
    def_foreststride = "once",
    def_alacrity = "once",
  },

  shaman = {
    def_lifevision = "on",
    def_spiritbond = "on",
    def_protection = "on",
    def_shaman_spiritsight = "once",
    def_lifebloom = "on",
    def_shaman_warding = "on",
  },

  shapeshifter = {
    def_weathering = "on",
    def_bodyheat = "once",
    def_metabolize = "once",
    def_celerity = "once",
    def_thickhide = "once",
    def_corner = "once",
    def_harden = "once",
    def_boneshaking = "once",
  },

  infiltrator = {
    def_warding = "once",
    def_finesse = "once",
    def_shadowsight = "once",
    def_ghost = "on",
    def_shroud = "on",
    def_lipreading = "on",
  },

  templar = {
    def_gripping = "once",
    def_maingauche = "once",
  },

  teradrim = {
    def_earthenform = "on",
    def_entwine = "on",
    def_ricochet = "on",
    def_twinsoul = "on",
    def_earth_resonance = "on",
    def_stonebind = "on",
    def_imbue_stonefury = "once",
    def_footfeel = "on",
    --def_sand_swelter = "once",
  },

  tidesage = {
    def_permafrost   = "on",
    def_wavebreaking = "on",
    def_tideflux     = "on",
    def_lifebond     = "on",
    def_shore_leave  = "on",
    def_encrusted    = "on",
    def_expose_rime  = "once",
    def_currents     = "on",
    --def_sirensong  = "once",
  },

  warden = {
    def_fearless          = "on",
    def_initiative        = "once",
    def_battleflow        = "once",
    def_ancest_victory    = "on",
    def_displacement      = "on",
    def_ancestral_bolster = "on",
    def_invocation        = "once",
    def_irongrip          = "once",
    --def_roaring  = "once",
    def_intervention      = "once",
    def_shroud            = "once",
    def_homage            = "on",
  },

  wayfarer = {
    def_ironskin = "on",
    def_weathering = "on",
    def_axe_obstruct = "on",
    def_brutality = "once",
    --def_blindsense = "on",
    --def_greenheart = "on",
    --def_endure = "once",
    --def_mountaineer = "on",
    --def_dustcoat = "on",
    --def_resilience = "on",
    --def_desolation = "on",
    --def_circulation = "on",
  },

  wolf = {
    def_weathering = "on",
    def_bodyheat = "once",
    def_metabolism = "once",
    def_celerity = "once",
    def_thickhide = "once",
    def_corner = "once",
    def_harden = "once",
    --def_stealth = "once",
    def_cloak_tattoo = "on",
    def_boneshaking = "once",
  },

  zealot = {
    def_focalmark = "on",
    def_tempered_body = "on",
    def_haste = "on",
    def_swagger = "once",
    def_litheness = "on",
    def_bending = "on",
    def_disunion = "on",
    def_clarity = "on",
    def_resurgence = "on",
    def_discharge = "on",
    def_deflection = "on",
    def_mindspark = "on",
  },

  predator = {
    def_spacing = "on",
    def_bladesurge = "on",
    --def_absorption = "on",
    def_regeneration = "on",
    def_secondwind = "on",
    def_windwalking = "on",
    def_preserval = "on",
    def_whitesight = "on",
    --def_defang = "on",
    def_culmination = "on",
    def_closecombat = "once",
  },
  siderealist = {
    def_luminesce = "on",
    def_blueshift = "on",
    def_foresight = "once",
    def_stargleam = "on",
  },

  executor = {
    def_irongrip = "once",
    def_bloodlust = "on",
    def_girded = "on",
    def_stoicism = "on",
    def_conceal = "once",
    def_deception = "once",
    def_vitality = "on",
    def_limberness = "once",
    def_bounding = "once",
    def_efficiency = "once",
  },

  voidseer = {
    def_irongrip = "once",
    def_erudition = "on",
    def_synergism = "on",
    def_introspection = "on",
    def_withstand = "on",
    def_vitalise = "on",
    def_occultism = "on",
  },

  --200s
  malevolent = {
    def_adherent_barrier = "on",
    def_adherent_presence = "on",
    def_adherent_synchroneity = "on",
    def_adherent_mortalfire_stored = "once",
    def_adherent_malevolence = "on",
  },
  strife = {
    def_adherent_barrier = "on",
    def_adherent_presence = "on",
    def_adherent_synchroneity = "on",
    def_adherent_mortalfire_stored = "once",
    def_adherent_turmoil = "on",
  },
  corruption = {
    def_adherent_barrier = "on",
    def_adherent_presence = "on",
    def_adherent_synchroneity = "on",
    def_adherent_mortalfire_stored = "once",
    def_adherent_acid = "on",
  },
  memory = {
    def_adherent_barrier = "on",
    def_adherent_presence = "on",
    def_adherent_synchroneity = "on",
    def_adherent_mortalfire_stored = "once",
    def_adherent_ruination = "on",
  },
  tyranny = {
    def_adherent_barrier = "on",
    def_adherent_presence = "on",
    def_adherent_synchroneity = "on",
    def_adherent_mortalfire_stored = "once",
    def_adherent_indomitable = "on",
  },
  instinct = {
    def_adherent_barrier = "on",
    def_adherent_presence = "on",
    def_adherent_synchroneity = "on",
    def_adherent_mortalfire_stored = "once",
    def_adherent_avengement = "on",
  },

  tiarna = {
    def_tiarna_bulwark = "on",
    def_tiarna_ruin = "on",
    def_tiarna_presence = "on",
    def_tiarna_shelter_stored = "once",
    def_tiarna_chimerism = "on",
  },
  glacian = {
    def_glacian_penumbra = "on",
    def_glacian_presence = "on",
    def_glacian_silhouette = "on",
    def_glacian_twilight = "on",
    def_glacian_adumbration_stored = "once",
  },
  aetherial = {
    def_aetherial_bastion = "on",
    def_aetherial_presence = "on",
    def_aetherial_torment = "on",
    def_aetherial_agility = "on",
    def_aetherial_band_stored = "once",
  },
  seraph = {
    def_seraph_radiate = "on",
    def_seraph_presence = "on",
    def_seraph_corona_stored = "once",
    def_seraph_parhelion = "on",
    def_seraph_halo = "on",
  },
  titan = {
    def_titan_disruption = "on",
    def_titan_irradiance = "on",
    def_titan_multicore = "on",
    def_titan_presence = "on",
    def_titan_remnant_stored = "once",
  },
  astral = {
    def_astral_chaosspores = "on",
    def_astral_dreamtide_stored = "once",
    def_astral_presence = "on",
    def_astral_recursion = "on",
    def_astral_refulgence = "on"
  },
  nocturn = {
    def_nocturn_haze = "on",
    def_nocturn_double = "on",
    def_nocturn_presence = "on",
    def_nocturn_bloodcoat = "on",
    def_nocturn_shadow_stored = "once",
  },
  sagani = {
    def_sagani_epicentre = "on",
    def_sagani_helix_stored = "once",
    def_sagani_presence = "on",
    def_sagani_similitude = "on",
    def_sagani_wall = "on",
  },
  chaos = {
    def_chaos_entropy = "on",
    def_chaos_figment_stored = "once",
    def_chaos_fork = "on",
    def_chaos_presence = "on",
    def_chaos_shroud = "on",
  }

}
