--5.533
--Fixed Wayfarer Assault adding/removing the extra damage on the first hit.
--Fixed the extra damage from assault adding to ranged attacks
--Added virulent to match vinelash calls
--Added Akkari and all its bits and bobs
--Added Ravager and all its components
--Fixed some Wayfarer patterns and inconsistencies (Lerad)
--Fixed references to limbs being 'broken' as a state instead of 'damaged' (aka 33% break) (Lerad)
--Updated path for Ollin for bashing/autowalking
--Updated the chatbox and map windows to allow for adjustable size/movements
--Fixed some pattern matching for Ascendril (Church)
--Fixed naming conventions where they'd been left the same as their mirror
--Condensed def tracking by 250+ triggers
--Went through GUI toggling and ensured it will load properly if snd.gui is not enabled.
--Fixed clawtwist/plexus limb damage
--Fixed autowalking to conform to mudlet mapper updates
--Added another prone line for rooms w/shallow water
--Fixed wayfaring shield usage order
--Added aff capture for cardinal + updated the namefix function to account for it being sent "a broken left leg" etc.
--Added lines for hellsight initial aff
--Added shadow to all attacks for luminaries
--Fixed some triggers being accidentally turned off on download
--Updated wayfarer bashing to use sustain even when shielding
--Updated epidermal to account for head/torso usage

--5.52
--Fixed a few sciomancer defenses
--Updated sciomancer and Ascendril bashing alias to more reliably utilize reflect
--Fixed a rather bad pattern matching bug for firelash that rendered its tracking useless
--Updated the color table ot better work with more addons/packages
--Updated some shadow side offenses/triggers/etc thanks to a package they were giving out.
--Added all info for Tidesage and Alchemist, though work in progress to ensure all is correct.
--Fixed an issue with one portion of the restoration tracking

--5.51
--Updated various Bard lines to match.
--Added shock/burnout to aff table.
--Removed firstaid elevation of certain affs - Sunder should be interacting directly with firstaid as little as possible in the generic download.
--Updated Bard aliases with a bit of extra calling and refined overall.
--Fixed inhibit/wraith triggers not removing shield.

--5.5 BRADS 
-- Added Bard skill tracking to 'all attacks'.
-- Added Bravado and Inspire to snd.cooldowns.
-- Added defense tracking (and all triggers) to scripts.
-- Added Song Timers to manage song-heavy Bard scripts.
-- Added 1 Bard 'support' route as a template.
-- Added 1 Bard 'team affs' route as a template.
-- Added 1 Bard 'team dmg' route as a template.
-- Between the above 3, someone should be able to figure out how to make SunderBard work for them on more personal levels. Hopefully.
-- Added defup and defenses for Bards.
-- We've tried to capture as much information as possible but there is a good chance not everything you need/want will be captured.

--5.4
-- Added an additional line to the variety of prones
-- Updated Elemancy Scorch to acknowledge emberbrand for limb breaks
-- Illumination Lightning aff corrected to allergies
-- Tweaked some Luminary/Earthcaller aliases that had incorrect or inefficient portions
-- Fixed the Warden version of glass limb, had the wrong matches.
-- Updated the aff called trigger to better support your random, weird formats for calling.
-- Fixed Ancestry Annul not checking proper class/skills.
-- Updated Elemancy Direfrost to include its failed case aff
-- Fixed the Lemniscate cure trigger.
-- Rage updated to include Templar, Revenant and Shapeshifter.
-- Added a balance variable for Sorcery Transfix
-- Added mobs for the Dyisen-Ashtan Memoryscape
-- Added a path for the Dyisen-Ashtan Memoryscape
-- Added exclusions on the 'got hit' trigger to not accidentally change curesets against 1 person
-- Added which limb was being hit to certain Sentinel attacks to better track parries
-- Support added for all current level 200 classes at the time of this changelog
-- Added support for all the new eucrasia affs

--5.36
--Updated Revenant items to use DPL instead of duplicity, missed in earlier transition of syntax updates
--Added doubleswing to Templar attacks
--Fixed superstition typo in pill cure order
--Added last_hit_limb to some sentinel attacks
--Added many more lines for templar/rev DSW/Fell
--Went through first pass of updating triggers to be more slim and less greedy for minor trigger engine matching speed boost
--Updated how often certain functions are called, removed superfluous checks
--Updated parameters for fitness/purge (Czcibor)
--Added Contort/Discord per changelog 1966
--Added timer functions to be used in scripting
--Added epilepsy line for Revenant
--Fixed rend always being given on 1p hits
--Added crippled/crippled_body aff relationship similar to paresis/paralysis
--Fixed destroyed_throat not having a check for the spot applied to

--5.35
--Added support for elemancy changes from announce 3245
--if you use flamewreathed_limb in anything make sure to reference flamewreathed.limb as a table value since we will also track current resonance used
--Changed "prone" to "fallen" for sentinel attacks to conform with previous changes
--Added shapeshifter to valid classes that can use rage
--Fixed starlight glaciaition proc having the wrong pattern
--Added more full support for generic mending applies to legs/arms for tracking
--Fixed some bad logic with rebounding proc not adding it back in all the time
--Updated items to comply with changelogs 1941 and 1943
--Fixed name database absolutely krangling itself w/regard to tethers

--5.34
--Added support for Earthcaller and mirrored triggers/aliases
--Added support for Earthcaller defenses and afflictions
--Added system wide support for aff counting functions
---- See snd.aff_count_all(), snd.aff_count_mental(), snd.aff_count_physical()
--Revised the alertness function to not spew forth errors if a name isn't tracked
--Fixed some odd behavior with Dhuriv, specifically dodge 1st hit and non venom second hit
--Tidied up snd.target_locked with cleaner logic
--Added parry being available to Dhuriv Crosscut
--Worked on attack picking logic for Sentinel, tried to tidy up. Will re-write when we have more time.
--Added support for Oneiromancer and mirrored triggers/aliases
--Added support for Oneiromancer defenses and afflictions
--Added support for self-affs for all mirror class afflictions
--Added more support for divulgence in 1p and 3p
--Reworked inspiration defense to be able to handle all stats appropriately and similar for battlehymn
--Added cooldown check to aeon/hourglass usage in indo/oneiro alias
--Updated lines/defenses for Oneiromancer that had been missed
--Updated 'a broken leg/arm' to 'a_crippled_(leg/arm)' to stay in line with other affs
--Fixed up some logic with dodge and sun/sphere moon/hypercube

--5.23
-- Updated API handling to handle changes due to changelog 1918
-- Added the alias 'update <who> (guild/city) <value>'
-- Added mining enemies in for use with bashing commands 
-- Added a "walkarea" command to walk around the current area without hitting stuff
-- Fixed some vampire deffing issues
-- Updated snd ndb handling on honors to not remove info it already has, though it may be outdated since it isn't in API

--5.22
-- Added eucrasia pill to basic tracking and aff list for worrywart
-- Fixed bending defense line ( had an extra space at the start ).
-- Added mobs for Eftehl
-- Added pah for Eftehl
-- Added weaponry lines for mace/morningstar that should alleviate non tracking of parry for Templar/Rev blunt
-- Fixed some logic issues with snd.last_limb_hit
-- Fixed a minor typo with overwatch defense
-- Added update to variable for purge usage
-- Fixed a bug with no_parry logic
-- Added a line for 3p weasel defense stripping
-- Updated skullbash and soulfire/soulburn to new affs
-- Fixed soulthirst and soulharvest
-- Added a 3p tracking line for accursed
-- Fixed skill usage per changelog 1915
-- Added mobs for Tak-re
-- Added path for Tak-re
-- Added mobs for Kkirrrr'shi Hive
-- Added path for Kkirrrr'shi Hive
-- Added a cooldown/balance tracker for crystal tattoo


--5.2 
-- Updated some toggles that weren't updating the gui
-- Updated handle_hounds to include blurry vision, separate frozen levels and ability to give/not give houndmark/tacticianmark
-- Added a line for paresis from warden version of reckless
-- Dstab wasn't tracking 3p correctly if the first attack was dodged, this has been fixed
-- Fixed revenant bashing function, had an extra letter
-- Removed assault_damage (extra damage after using tenacity assault) properly when applied
-- Fixed some matching issues with Ascendril (esp Firelash)
-- Fixed some revenant checks still looking for Templar
-- Fixed revenant skills not having 'chiro' before them in one alias
-- Added some situational affs for Ascendril skills (church)
-- Added lines for ice_encased, thunderbrand and emberbrand (church)
-- Fixed a damaged limb line setting the wrong table value
-- Removed the necessity of the bashing paths file as it is now in the system, all 10000 lines of numbers

--5.1
--Removed shadowslip from active defenses
--Added an alias to remove a single person from the database, no questions asked (Val)
--Changed alertness procs to only call if different tether or rogue(Sryaen)
--Updated cwho trigger based on suggestions(Deva)
--Fixed enemy name still showing up, was missing gui check(Deva)
--Added Indorani defenses to the priority queue, oops
--Added shivering/frozen 1p line from decay
--Added a missing battleaxe hit confirm line
--Removed the silly old trigger to re-wield a shortsword if you lost wielding of anything
--Fixed teradrim bashing function
--updated some untargetted mending lines and logic
--Added a check for heatspear to ablaze curing
--Made some updates to QWP and related functions to accomodate level 20 goggle users.
----It checks the current QW instead of pinging the website, offering a clearer view.
--Went through Teradrim attacks, all values are the base without inks and work properly with my testing (alone, so maybe not perfect). If you want to change numbers to accomodate those, go for it.
--Went through Indorani deffing to try and make it not so spammy. I was dumb, don't ask.
--Added an alias to move to next area while using custom bashing routes if you want to skip the current one for whatever reason.
--Fixed sand swelter trying to defup without having sand down
--Fixed absorb ylem queue for those who don't have the gauntlet w/insta absorb lmao 400 credits well spent amirite 
--Removed oberglot from Djeir catacombs targets as you can't kill it or something (Rhine)
--Fixed the bio steroid trigger to remove qeb, needs to be used while off balance
--Fixed matching cases for battleaxe (same as previous weapon types in 5.07, just missed) (Sryaen)
--Added new mobs to Dovan which suck and make you bleed way too much to be worthwhile
--Fixed Augerweald path to run the whole area
--Added path for basilisk den and targets
--Added path for maul and updated targets
--Added path for forgotten depths of mount helba and targets
--Added path for bakal chasm and targets
--Went through many triggers that delete lines or substitute and curated to try and cut down on losing information that is helpful in logs
--Similar to above, changed some echos to be a bit more reading friendly and have key information pop.
--Added a cooldown tracker for fulcrum enrich for Ascendril, yay resonance nonsense
--Worked on Ascendril affliction stuff for groups
--converted people in room(group only check) to function for easier usage in more areas
--I made some big changes to called affs to combat removing affs on dodge that were already on target from previous round. It was a weird edge case that required some silly solutions but it works great.
--Updated Tenacity Devastate to account for all the messages+maybe venom application
--Fixed the exp trigger to account for config prettynumbers(Charica)
--Updated one of the monk parry lines(charica)
--Added rebounding removal to boosted threaten(Valeria)
--Fixed survival restore to actually fix all limbs applicable instead of just one, oops
--Converted the snd.target_prone boolean variable to instead apply the "fallen" affliction, helping to separate cases where this distinction is necessary
--Converted all writhe affs to be preceded by writhe_ to better work with the affliction names in game.
--Updated no_parry() and proned() to include all affs that should be applicable
--Changed all instances of "a broken right/left leg/arm" to instead use the aetolian variant, left_leg_crippled and etc.
--Self-pity will be recognized in the system as self_pity for conformity reasons
--Added a function to more easily fix aff names so they don't need to be fixed in every instance
--Templar affs mental/physical disrupt and crippled body similarly use _ instead of spaces
--Added an alias to make logging lessers less of a chore! loglesser (names with spaces) will sort and log for you.
--Fixed some of the matching cases associated with limb breaks
--Fixed check for cracked_ribs not using the right match
--Updated mending, soothing and restoration to work with angel sear
--Added a level check to raceskill list
--Moved empowerments to their own table to better handle revenant/templar swapsies
--Added all items for revenant
--Added all items for warden
--Fixed up hound functions to work for both wardn/carni without adding too much bloat
--Removed snd.hounds for hound switching since it was no longer necessary
--Fixed up warding maul wargauntlets matching to fit 1p and 3p
--Fixed poultice trigger having commented out the cure method for salves, oops
--Added trigger for frost hits from warding anoint
--Fixed Revenant maingauche trying to def improperly based on a typo
--There was a change in syntax from the original version of chirography skills compared to what was released. 
--     As a result, some offense aliases won't scribe releases (vorpal/crescent etc) correctly and has been fixed.
-- Fixed an issue with Warding Terrorize not tracking appropriately.
-- Fixed Sunder not checking certain skills for whether or not you had access, had commented it out for testing purposes.
-- Fixed handle_hounds not giving houndmark/tacticianmark, also commented out for test purposes.
-- Tidied up one more line for Warding Maul.
-- Converted places where toggles were hard set to true or false to use the toggle function so the GUI could update appropriately.
-- Added renown farming for Wardens
-- Updated shaman bear spirit to regex type matching, was set to substring
-- Fixed a remaining instance of gui_loaded to the proper handling
-- Updated another warding line. Why are the 1st and 3rd person messages so different?
-- Added the fallen line for when roaring procs on warding attacks
-- Made sure voidgaze secondary aff trigger was always on
-- Altered a resistance trigger that was checking snd.getting_hit instead of the name in the line

--5.07
--Fixed matching cases for rapier, flyssa and scimitars for templar attacks (Drystin)
--Fixed consistency issues with lovers effect (Illidan)
--Added fury expunge cure tracking and updated the physical aff list to the correct order (Illidan)
--Fixed tenacity attacks not tracking appropriately as they were calling snd.effects instead of venomeffects (Drystin)

--5.06
--Fixed a small error in the line for desiccation shred (limb) vs (limb storm) to account for either(Ipz)
--Added a toggle to automatically reject lust or not (toggle reject) (Illidan)
--Fixed a wrong matches check in deliverance trigger (Rhine)
--Fixed the baying trigger trying to afflict damage howl (Rhine)
--Fixed the lycan resisting breaks trigger, had wrong matches (Rhine)
--Changed up some monk defenses to try and fix issue with deffing up(Courene)

--5.05
--Added the Squal area mobs and area path
--Whitelisting off names for chatting proves not great for newbies/divine/admin changed to any one word name to weed out most npcs (Czcibor)
--Added lines to shapeshifter defs to make sure they're accurately tracked (Saybre)
--Modified the honors/auto highlighting function based off suggestions (Czcibor)
--Added hypersight defense (Drystin)
--Added toggle/namedatabase/bashing save functions to QQ since sometimes Mudlet is closed before disconnect event


--5.04
--Added the bending defense for Zealots, added bending and mindspark to priorities
--Fixed up the defense list options a bit

--5
--Added "generic broken arm/leg" affs and ways to track such things
--Fixed config groupmove -> leading skill
--Changed up the way ferality is tracked to make it a bit easier going forward
--Removed a gag for deleting lines that deleted the lines that affs would be added on
--Added class checking via GMCP to make Sunder always know
--Added some extra rebounding checks to ensure tracked on 3rd party attacks
--Transitioned to name database instead of hard coded table
--Removed the usage of snd.allies, snd.enemies, snd.set_faction to instead use gmcp and name database tether checks
--Above possible thanks to Sanir's foundation for the database. Thanks, Sanir!
--Updated target calling to use target list given, if no targets in list then it tracks first target of opposite tether in room
--Added checks to see if the Sunder GUI was enabled for all containers, chat and updating mechanisms
--Converted defenses to check if your character has the skill before trying to execute the defense
--** Some items are noted as having "Generic" as their skill, such as plants and elixirs. It is auto assumed you have those.
--Will automatically check Raceskills to use those if you have them
--Will automatically check Tattoos to use those if you have them
--Will not try to parry unless you are able to with the skills associated
--Archivist basic group aff route updated and fleshed out 
--Archivist madness moved to the snd.balance frame
--Fixed Sentinel triggers not getting the dodge/parry to remove affs on venoms appropriately
--Won't try to grab staked corpsed
--Somehow didn't have 3p syssin bite, only had 1p
--Added some extra flay lines to confirm def loss
--Added 3p swagger removing paresis
--Fixed up tenacity attacks to have more check for venom calls
--Rejoice, for I have changed it to utilize GMCP for tells/etc tracking
--Questing toggle put in. NO MORE KESTREL WHISTLING FFS
--Changed the numpad keys to be a bit easier and also add a LOOK option without typing it
--Re-sized GUI elements, including making the people sort much taller to account for 15-20 people in a room on one tether
--Removed scepter toggle and bashing, shit was nerfed a while ago
--Added easier way to toggle many things, via just 'toggle <item<' that works in addition to regular aliases
--Removed zeal for the same reason as sceptre
--Moved where aegis is checked onto gmcp instead of randomly thrown into the queue
--Added lipreading to Syssin defenses + priority queue
--Made def options into separate of generic vs class based, will add both when you defup
--Worked on GMCP for wielding weapons to be more specific and not randomly assign values
--Changed how it handles sileris deffing because of separator shenanigans
--Updated guarding line for all attacks that may hit it
--Added helpfiles for many aspects of sunder along with expected behaviors and examples
--Removed the manual sorting button under shadow/spirit to give more space
--Updated indorani stuff cause the old one was booty
--fixed removing the wrong people from room on death
--added more areas to bashing + added them to be auto-pathable
--fixed angel battle to use combat messages
--added angel battle to balance tracking
--fixed snd.target_gone to set properly on not finding target to hit
--luminary smite for pure damage alias done
--updated experience gain trigger to work on player kills
--fixed the balance echo trigger to actually show balance times
--added gagged lines to reduce on spam, including gagging non-target general cures(focus, tree, etc)
--fixed templars being able to use many kinds of weapons for some of the aliases
--going through darkside to take out things they may have that I don't
----pulled over a bunch of quests, some random defenses, vermin auto movement
--Updated restoration handling to be able to kill process when we switch targets
--Added support to track sTuPiDItY bUlLsHiT over webtells for target calls and affs both
--GMCP communication spruced up and tightened to not capture erroneous data
--Fixed display of self prone being colored on target prone
--Added names to ignore for highlighting -- fixed further below
--Added next target with skip for targets in room that caller wants to bypass
--toggle for aegis added
--Added howl tracking, thanks Saybre!
--Fixed inadvertent hit messages on weapon hits without target in line
--Fixed venoms given from dhuriv hits
--Fixed up rebounding issues and tracking from dhuriv hits
--Sunder aff table now has support for all afflictions on AFFLICT LIST if someone messes with the curing
--Updated wayfarer tracking to account for limb damage
--Made a basic execute focused limb alias for wayfarers
--Fixed caloric tracking due to changes in hypothermia/ice_encased
--Removed hidden/phase checks on backstab
--fixed some typos in displays
--made 'sunder help' update the name/class display at the top if it ever gets wonky
--Changed how doublestab is being tracked to make it a bit more smoothe..so far at least
--Fixed shaman effusion pattern
--Added the lifebane removal line rather than using a timer
--added checks for removing affs/defs if you die/are dead
--Added aegis rope writhe aff
--Added a small check to auto target functionality
--Added a check to dispersing so that you don't try to disperse yourself or get an error while doing so
--Fixed sentinel bear->direwolf for daunt
--Changed gmcp communication to whitelist off of names in database for capturing rather than blacklisting all the talkative npcs
--Updated the gui
--Added fury sustain to wayfarer bashing because it's amazing


--4.18
--Added regenerate tracking to restoration salve
--Removed extra ironskin defense line trigger
--Fixed ironskin defense command 
--Fixed spheres not working properly for Archivist
--Added an alias to check score to fix snd.class not properly getting set 
--Updated the Vortex path to include the area with treants
--Added the def line for zealot resurgence
--Added Zealot indifference via Psionics Dull
--Added telepathy affs and states (attempting lock, locked, clamped)
--Added telepathy balances (command, cleanse, push)
--Added kaido balances (strike, cripple)
--Added kaido aff lines and updates old ones
--Added Tekura tracking for aff attacks and numb_arms tracking
--Added fend to self-parry trigger
--Added a few catches to quickwield/quickunwield to update GUI
--Added flame tattoo as a defense that you can use (flame_tattoo)
--Potentially fixed tracking for Zealot limb damage 3p on parried attacks, need to keep track
--Fixed direblow trigger not working correctly for 1p
--Removed haven point on experience gain if not above level 99
--Added who group parsing ("who groups") via Czcibor
--Fixed rend tracking to have a bit more leeway between venoms or actual rend
--Added more room suggestions for a different farsee
--Fixed tree line (apparently it changed?)
--Tentative counterattack protection
--Added an aetolia specific line to water mudletmap movement

--4.17
--Aegis function, assumes your city has it turned on (why wouldn't they?)
--Will auto aegis if you're attacking and meet certain criteria
--Fixed a few kaido triggers based on changelog 1670
--Fixed Sentinel reave due to undocumented change making the trigger different
--Fleshed out Sentinel offense to incorporate more attacks and not just spam trample

--4.16
--Updated wayfare defs
--Added tree/salve_seared

--4.15
--Added a fishing trigger that was missing
--Fixed shaman deffing

--4.14
--Added automatic dispersing with a toggle

--4.13
--Updated some Zealot attacks/triggers that were previously missed
--Updated/strenghtened restoration handling
--Went through each updated trigger with the pronoun change to account for (the racename) and fixed the matches on each.

--4.12
--Fixing random triggers that broke because of the changes below for pronouns
--Added survivor mobs and some weird eld to global targets

--4.11
--Conform to CONFIG PRONOUN - changed every he|her his|her etc to just be \w+.
--Fixed relic entangle/webspray not properly working

--4.10
--Added a safety to QL if it tries to target someone who it hasn't caught as leaving (evade, etc)
--Fixed deepwound not applying correctly for 1p
--Fixed dislocate on mending trigger, was using wrong function name.
--Updated to a new version of ascendril offenses courtesy of Hallis

--4.09
--Just debugging. Nothing major changed.

--4.08
--Alright, I swear to whatever god may listen to text rants, if the calling hasn't been fixed because GMCP is a POS at times, I'm going to 
--Fixed raloth limb breaking trigger to correctly capture breaks
--Updated Ascendril offenses

--4.07
--Fixed miasma/warmth/safeguard to not overlap each other constantly
--Made some changes to target calling w/debugging information to try and track down some problems

--4.06
--Fixed target calling AGAIN. Used the wrong variable.
--Fixed the route for gogo low
--Updated defenses to auto add miasma/safeguard/warmth based on race

--4.05
--Updated crippled_throat to 'crippled throat' for ease of use/tracking.
--Added sparklight into tables of mobs
--Fixed basher not actually changing the correct path

--4.04
--Updated the bashing loop to include two options. You can either choose an easier, longer path, or an endgame, xp focused path.
--Checks automatically if you don't pick either.
--Continued working on Ascendril.
--Fixed/changed method of target call over web changing target.

--4.03
--Fixed a bug with enemy aff displaying multiples of the same
--Fixed up ascendril offenses
--Added fulcrum flare triggers
--Focus now properly cures muddled
--Made a force to use miasma/warmth based on endgame race, it was just way easier this way

--4.02
--Updated ascendril aliases to use the already made system for defenses to check if a spell is stalled
--Fixed target affliction tracker which was messing up the removing of affs
--Fixed up the ylem path to remove an inaccessible location

--4.0
--Changed the "people in room" area to separate to shadow/spirit.
--It uses snd.shadow and snd.spirit primarily.
--WARNING - if there is someone that is not on the list, it will pull information from the Aetolia API to check their city.
--To do this, the function creates a small document (that it deletes once finished) in your home directory - use getMudletHomeDir() to check.
--Fixed soothing trigger to not proc on mending, whoops
--Changed ldd to also accept 'defup'. Will load based on class if no argument specified.
--halp has been updated and fleshed out
--?pk has been made and will show aliases for different modes with basic descriptions based on snd.class
--Added timing delays to 'fake call' and 'prismatic barrier' as spam is a friend of nobody, except..vegans or something? idk nobody reads changelogs anyways
--Lycan tracking should be fixed for the case of it retaining affs and removing the wrong ones on parry/resist
--Fixed an issue with Kai Cripple where we were using the wrong match and it wasn't tracking properly
--Updated checking target list with GMCP instead of who here.
--I think deffing is fixed after death? Maybe?
--The "people here" box in the bottom left should accurately update now. -dirty rotten lies but ITS FIXED maybe -- double fix, see below
--Fixed up the wayfarer aff support to utilize a bit more of the kit
--Added 1p shaman vinelash tracking
--Updated Carnifex hound handling with proper affs and it uses stuff other than contagion
--Combined Carnifex hound aff triggers into 1 so it'll track 1p and 3p affs
--Fixed a typo in the zeal chain attacks
--Fixed Zealot affs not clearing properly on new attacks, which would let parries on attack 2 clear attack 1
--Added Zealot Rejection to rebounding lines
--Opened up the bite trigger so it didn't break on artifact fangs and etc
--The goylem functions shouldn't loop now if you try it while in a city. You will need to GOYLEM START to restart it.
--Added a mounted check based on gmcp to above movement function.
--Added/updated area mobs to the bashing table: 
--Arbothia, Drakuum, Ollin, Kalydian, Maghuir Fissure, Torturer's Caverns, Mamashi, Three Rock, Ia'shal, Tcanna
--Shadow has weird calling habits and likes to call their class. Sunder will now recognize those aff calls appropriately.
--Added swirl/mental disrupt to 1p tracking
--Added research disperse to clear all writhes upon use on target by their ally
--Changed 'on' and 'off' to 'sndon' and 'sndoff' after a suggestion by Ehtias, thanks! No more accidentally turning stuff off or being unable to do certain things.
--The Shadowfiends are upon us. Huge influx of triggers for shadow based classes, including defenses and afflictions.
--Made the defense table a bit easier to navigate by separating most of the defenses per class
--Fixed up vinelash 3rd person hit confirmation
--Added finesse to track and undo properly
--Added the ability to call mobs by number with taget calling enabled (alias 'tcl')
--Fixed up the tracking of folks in room to separate shadow and spirit.
--If it finds someone that it doesn't have in snd.spirit/snd.shadow, it will download a text file of their information to your mudlet directory
--And check their city upon completion, as well as add them to a list. Click on the "New people to sort" to get info of who they are and where they go!
--Updated enemy affs to properly change colors for the lock affs (paralysis, asthma, stupidity, anorexia), as well as prone/pseudo prone
--Updated enemy limb tracker to display different colors for levels of breaks

--Added the function snd.checksomeAffs. 
--It accepts a list of affs in a table, along with a 2nd argument of a number of affs it needs to hit to return true
--For example: snd.checksomeAffs({"slickness","clumsiness", "hypochondria", "weariness", "paresis"}, 2)
--This will return true if 2 of the affs are hit, at minimum. This allows you to open up your aff checking and not be rigid.
--

--3.7 We did stuff here, a lot of stuff, but it got lost somewhere.

--3.6 (The Sentinel update)
--Moved where afflictions are added in snd.target_got so the display panel on left is updated for affs as they are on hit, rather than missing the last aff hit with
--Added prone to the display panel using snd.target_prone and checks in adding/removing affs
--Added ways to have display update removing prone because it's a pain in the neck ('not prone' and 'stood' triggers)
--Added sentinel defs (barksin, flexibility, lifesap, maskedscent, conceal, hardiness) and def lines
--Added sent defup option
--Added more limb break lines
--Added daunt and flourish handling along with daunt aff tracking
--Moved Sentinel aff picking to script to better facility special cases if they want to be made, an example is included
--Added icebreath/salve(trample for groups) offense for sentinels
--Removed some code from tfix+sensi for sentinel so it is more in line with the other modes
--Switched to GMCP for webtell target checking, removing the need to color check.
--Added tenacity/fury tracking
--Switched around and updated the target list

--3.5 (Templuminary additions)
--Updated vine entangle/webspray lines to confirm with changes in changelog 1505
--Implementing better group offenses - Templar/Luminary - Group impale and group aff
--Rewrote some handling of Luminary attacks, added crash, 1p dazzle
--Added snd.all_affs to easier check how many affs are on target
--Added Dhuriv Weaken to tracking

--3.4 (Anti-illusion crusade)
--Added in more customizable Sentinel offense
--Added/fixed Dhuriv attacks to track
--Added some Dhuriv specific curing to appropriate methods
--Updated prismatic handling to include another Templar specific attack
--Added hourglass handling including checking if an hourglass is inked on login
--Added automatic webtell color check and target call check to try to stop illusions -- this has been updated again in 3.6
--Added and fixed some raze tracking issues
--Will start calling affs again on new target switch instead of previous methodology
--Added a Shaman prone, another transfix line which may be overkill

--v3.3
--Added a counter for neckdrag.
--Fixed a bug that occasionally doubled up venoms if you only needed one to lock.
--Updated the lists of spirit/shadow players.
--Fixed a bug with void and ineffective cures in the same prompt as real ones.
--Added angel sacrifice to both 1p and 3p aff tracking cures.
--Added evoke cleansing for luminaries.
--Totally reworked the luminary group offenses.
--Fixed a bug that prevented accurately tracking class/faction on login.
--Added special onslaught eld to the top of the global target list.
--Added a very basic wayfarer offense.
--Expanded the 'halp' alias to include a lot of useful commands.
--Fixed a bug preventing targets from loading in the Shattered Vortex.

--v3.2
--Reworked afftracking for venoms/effects that give more than one aff.
--Improved tracking of flay for syssin.
--Cleaned up all syssin and a bunch of templar offenses.
--Updated how sunder tracks afflictions on target.
--Finished adding all of the weaponry hit lines.
--Further improved 3p affliction tracking with safety checks for luminaries.
--Improved re-queuing logic to avoid hitting rebounding, specifically.

--v3.1
--Improved the parrying even further.
--Expanded the templar 'ret' offense a little more.
--Fixed a bug that occasionally broke the system under certain parry conditions.
--Tidied and updated the templar dmg and zl aliases.
--Added more templar wielding options.
--Made some changes to how target_locked and missingAff functions work.
--Completely revamped third person attack tracking.
--Totally redid how sunder chooses which effects to use in a given round.

--v3.0: Daren's coup
--Reorganized a bunch of folders.
--Added a feature where FC will display missing venoms.
--Hooked up the exit-tracking window in the GUI.
--Added tracking of cube sigils in room.
--Fixed several minor bugs in affliction and prone tracking.
--Fixed some issues with the my and enemy affs windows, they display properly now.
--Updated the bashing table to reflect the previous changes from IH to GMCP.
--Made the melting call a little less obnoxious/frequent.
--Added some new tools like missingAff and target_locked for building offenses.
--Made some major changes to the 3p curing tracking, it's much more accurate now.
--Completely revamped the templar 'ret' offense.
--Improved the parry handling a little.

--v2.3
--Improved the attack queuing to update better as target status changes.
--Added a couple of syssin affliction-based offenses.
--Cleaned up a bunch of junk with global variables, converting to local where possible.
--Added monk defenses and a monk defense profile. Thanks Kalinaar!
--Expanded the alerts to include some other important conditions.
--Sunder will now attempt to automatically set your faction, making it more plug-and-play.

--v2.2
--Cleaned up handling of the toggles window, it should be more accurate now.
--Added some syssin defenses and QOL stuff. Thanks Daren!
--Added a basic syssin damage offense (dmg) for opportunistic garrotes.
--Added some firstaid elevate functionality for panicky stages in a few affs.
--The basher now runs off GMCP - may be some lingering bugs with this change, let me know.
--Apothecaries rejoice! There's not a 'global' target list!
--Added a questing module and some quest triggers and handling. Neat stuff.
--Added a new landmark system, you can set as many as you like now and pt <landmark>.
--  o Find the list in scripts->sunder->core->variables->landmarks
--Defended attacks will no long have their afflictions tracked.
--Sunder will now handle shrugging for syssin.

--v2.1
--Corrected a syntax error in absolve for lumis. Thanks Oonagh!
--Dramatically improved shifter tracking and offense. Thanks Taaroshi!
--Mjoll linked up the myaff and enemy aff windows. Thanks Mjoll!
--Fixed up some stuff with a couple of the templar offenses.
--Added some more 1p sentinel tracking. Thanks Stine!
--Also woodlore aff tracking. Also from Stine!
--Added more Carnifex defenses. Thanks Dagun!
--Added a new alias, 'grp', which lets you set a bashing group. Use grp none to clear it.
--Improved the 'wielded' tracking window, it's ALMOST always accurate now.
--Got the toggles windows working on the GUI - it's now officially over halfway functional!

--v2.0
--Fixed a bug with handling necromancy shrivel. Sorry :(
--Added some QOL aliases for lumi, like beckon and stuff.
--Added 3p dstab afftracking.
--Fixed an issue with looped target calling if listening to each other.
--Added mindnet and fullsense calls.
--Cleaned up alertness logic.
--Added directional keys.
--Target calling will now also make you pick up/drop monos on movement.
--Fixed a bug with shield swapping for lumi.
--Subjected myself to geyser :( Cleaned up the chat box a lot.
--Sunder now has an actual GUI. Not all of it works yet! COMING SOON (TM).
--Added tracking for monolith sigil in room.
--Added wielding tracking. Still slightly buggy, working on it!
--Added a new utilities folder with some stuff for toxicology.
--Sunder is now packaged in modules, though I'll also maintain a full package.
  --NOTE! I'm expecting bugs with this, please try it out and report errors!
--Fixed a bug with tekura bashing. Apparently there was no cobra toggle.
--The ls alias now supports multiple target callers.

--v1.6
--Added luminary class defenses and ldd lumi option.
--Fixed some stuff to make lumi shield-swapping cleaner.
--Added a couple of basic group offenses for monks.
--Removed blind/deaf from def options as firstaid handles it.
--Adjusted 'newb' mode for templars to cheese impale instead of just affs.
--Fixed a bug with uncalled 3p attacks adding random affs.
--Added first and third person aff tracking for sentinels.
--Made a sentinel version of ms and dmg both.

--v1.5
--Added chasten after overwhelm for lumi offenses.
--Added another zealot group offense, dmg.
--Added ln as a lunge alias.
--Added some serious alerts and echoes for radiance.
--Added an echo for parsing alertness.
--Fixed a bug with class tracking.
--Fixed a bug with rejecting lust tarot.
--Added some stuff to try and rescue allies in need.
--Added a luminary alias 'fs' to perform force stop.
--Added luminary perform force kick on prismatic barrier.
--Luminary group mode will now swap between shields as needed.
--Zealots and monks will GUARD instead of PARRY.
--Added a dmg alias for shapeshifters, too.

--v1.4
--Fixed a bug with shaman afftracking.
--Added a newb offense for Ascendril.
--Added auto class tracking, no more need to change.
--Cleaned up fitness handling, won't try it if you can't now.
--Added basic zealot support and mouse mode.
--Added a couple zones to the basher. Thanks Aeraisentesh!
--Added some support for firstaid to handle shrivel better.

--v1.3
--Cleaned up luminary first-person tracking.
--Added a mouse mode for luminary.
--Added mouse mode for ascendril, too.
--Affcalling will call blaze now for templars.
--Afftracking will track said blaze calls from templars.
--Added minimal shaman support, with mouse mode.
--Cleaned up some stuff with melting calls.
--Fixed an issue with web re-invite spam.

--v1.2
--Added support for shapeshifter defenses.
--Added shifter bashing.
--Fixed a bug with the fangbarrier defense.
--Added an alert for high madness while shifter.
--MUTATE/REVERT will now swap snd.class automatically.
--Fixed the spam issue with arti pipes when lighting is toggled on.

--v1.1.1 (hotfixes)
--Added a better cooldown to panic alerts.
--Added some more checks to the auto-web-invite.
--Removed PvE target calls.
--Fitness toggle will now actually toggle use of fitness.
--Added a scepter toggle for bashing.

--v1.1
--Fixed a major issue with afftracking and rebounding aura.
--Added a new ms alias to templars.
--Expanded afftracking to allow for prone conditions.
--Added a dummy mode generic offense that just punches repeatedly.
--Added entanglement tracking.
--Distinguished between paresis and paralysis for afftracking.
--Added a panic toggle that cries for help as needed.
--Added class-based auto-defend for panicking allies.
--Added some UNDEFEND checks, too.
--Made impale attempts check for physical affs to extend writhe.
--Added auto-web-invite if an ally web quits while attacking.

--v1.0 (out of alpha!)
--Added support for Carnifex.
--Added Carnifex limb and aff routes.
--Added Carnifex third person tracking for limbs and affs.
--Added snd.faction to toggle faction-based functions.
--Added warhound handling! Woo puppies!
--Corrected some errors in tracking a couple defenses.
--Fixed a bug with clearing affs on re-targeting.
--Expanded the list of spirit-side players.
--Added target following with the ls alias (ls off to turn off).
--Added Ayhesa to the pather for bashing.
--Cleaned up some offense options and checks for easier use.

--v0.7
--Fixed several tracking issues with people leaving the room.
--Added a new templar offense route, mg, for magic-based classes.
--Combined the iceblast and stun limb offenses. Super offense!
--Added proper tracking of shivering/frozen affs on target.
--Dramatically changed limb route logic - again.
--Fixed a bug with auto-calling and lyres. Oh the spam.

--v0.6
--Dramatically cleaned up 1p attack echoes. Whew.
--Tweaked templar bashing to support DSK too.
--Added fitness toggle and use of it.
--Started working on the questing module.
--Fixed a bug with the ylem hunter not using leylines.
--Added basic luminary offense stuff.

--v0.5 (beta!)
--Did a total rewrite. Omg.
--Fixed so many bugs. Can't remember them all.
--Cleaned up a lot of unnecessary or redundant variables.
--Added a wield alias for limb weapons.
--Made some major adjustments to limb offense, much nicer now.
--Added some toggles, like newbie and parrying.
--Added third-person luminary aff tracking.

--v0.4.1
--Added basic templar limb offense.

--v0.4 (alpha)
--Cleaned up eld shackling, it's pretty smart now.
--Removed the pile of manure from the ylem hunter.
--Added Nal'jin Depths to the auto basher.
--Added soul substitute for resetting offense.
--Replaced a bunch of ylem-related lines to reduce spam.
--Added a more obvious alert for prismatic barriers.
--Added lower Tiyen to the basher too.
--Added sight as a valid aff. Yay transfix.
--Added new offense options: mana, jesus, legs, and arms.
--Added rudimentary auto-calling.
--Cleaned up a bunch of spammy junk.

--v0.3 (pre-alpha)
--Added a bunch of dead people checks to stop the offense junk.
--Seriously cleaned up the ylem hunter. Like a lot.
--Sank some time into optimizing the zeal offense.
--Added target calling, and an anti-illusion check for it.
--Tweaked the scent calling to ignore your current room.

--v0.2 (pre-pre-alpha)
--Added lots more paths to the basher. Yay bashing.
--Added elemancy reflection to razing, and third person aff tracking.
--Also, added razing to third person tracking, to avoid doing it double.
--Refined some of the venom stacks, specifically the 'ret' one.
--Added more subs, colors, and echoes to reduce spam.
--Put in a prone check to STAND while bashing.
--Worked up a currently primitive ylem hunter thing.
