cecho("\n<CadetBlue>Sunder War")
cecho("\n<MediumSeaGreen>---------------")
cecho("\n")
cecho("\n<MediumTurquoise>The commands are as follows")
cecho("\n")
cecho("\n<DeepSkyBlue>war division <divisionNumber>  <ForestGreen>Set your tracked division")
cecho("\n<DeepSkyBlue>war destination <vNum>         <ForestGreen>Set the room number for your division's destination")
cecho("\n<DeepSkyBlue>mt <dir>                       <ForestGreen>March division in direction")
cecho("\n<DeepSkyBlue>war kill <enemyDivision>       <ForestGreen>Start the slaughter")
cecho("\n<DeepSkyBlue>war fort                       <ForestGreen>Order your division to fortify")
cecho("\n<DeepSkyBlue>war order <order>              <ForestGreen>General catchall, will order your division anything you give it")
cecho("\n<DeepSkyBlue>War package created by <purple>Teflin Vyktaire")
cecho("\n")
cecho("\n<MediumSeaGreen>---------------------------------------")