cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>Calling <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>----------------------------------------")
cecho("\n<ForestGreen>In previous iterations of Sunder, we used static calling lists that were susceptible to failure due to not having new people updated, people switching tethers, needing different orders, etc. To that end, we have updated our methodology and you may find all of the ways to manipulate targets below.")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>tcl                   <ForestGreen>Turn on automatic target calling.")
cecho("\n")
cecho("\n<DeepSkyBlue>atl [name]<ForestGreen>            Add targets in the priority you specify.")
cecho("\n              <white>        Example > <red>atl ezreal nazeebo meepo")
cecho("\n<DeepSkyBlue>atp [name] [position]<ForestGreen> Add target with/without a # value for priority.")
cecho("\n              <white>        Example > <red>atp tryndamere 1")
cecho("\n<DeepSkyBlue>tlist<ForestGreen>                 List your targets in web for others.")
cecho("\n<DeepSkyBlue>atlc<ForestGreen>                  Clears your targets out to start over.")
cecho("\n<DeepSkyBlue>atr<ForestGreen>                   Remove a singular target from your list.")
cecho("\n")
cecho("\n<DeepSkyBlue>nt<ForestGreen>                    Manually skip to the next target in line.")
cecho("\n")
cecho("\n<MediumSeaGreen>----------------------------------------")