cecho("<CadetBlue>Welcome to the <green>Sunder <DeepSkyBlue>PvP<CadetBlue> help file!")
cecho("\n<MediumSeaGreen>------------------------------------------")
cecho("\n<green>Sunder <ForestGreen>has several built in ways for every class to be, at some level, useful. Even if it is just automatically attacking a target with a bashing attack. <green>Sunder <ForestGreen>is not and will not be updated with the best 1v1 PvP methods, nor will requests for 1v1 specific items be given time. The intent of Sunder has been and always will be the ability for the average player to get into the PvP scene at the lowest level and be able to participate in team scenarios.")
cecho("\n")
cecho("\n<red>Some of the classes have decently fine-tuned aliases (Syssin, Templar) due to the original creator  spending time in those classes. Remember that these were built on the effort of another player and they do not speak to your own skill or development. Using them to beat people at the low or middle tier of skill level does not indicate that you are improving. If you are interested in learning to PvP in the 1v1 arena, your best bet is to examine what is built here and expand or change it as opposed to relying on it without modification. These are public offenses and people can and will abuse their access to them to make it easy to beat you.")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<DeepSkyBlue>ls <person>                         <ForestGreen>Choose your target caller(s)")
cecho("\n<DeepSkyBlue>ls stine vaessa bob                 <ForestGreen>Example of listening to more than one person.")
cecho("\n<DeepSkyBlue>loc                                 <ForestGreen>Need help?! Call out your place in the world over web!")
cecho("\n<DeepSkyBlue>acl                                 <ForestGreen>Toggle calling of afflictions over web.")
cecho("\n<DeepSkyBlue>tcl                                 <ForestGreen>Toggle calling of targets over web.")
cecho("\n<DeepSkyBlue>toggles disperse <none/callers/all> <ForestGreen>Automatic dispersing of writhe affs.")
cecho("\n                                    <ForestGreen>Default none. Not always necessary.")
cecho("\n")
cecho("\n<green>Sunder<ForestGreen> target calling - instead of the old rigid lists found within Sunder, we will now utilize the custom, on the fly lists along with our name database to be able to cycle through targets effectively in the room. Please see <DeepSkyBlue>sunder help calling<ForestGreen> for more information on using that.")
cecho("\n")
cecho("\n<green>Sunder<ForestGreen> has the following aliases available for you to use in combat. There may be more aliases included in the settings, but not always!")

if snd.class == "Monk" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>aff<white>                - Will use mind batter to hit with affs, if enemy prone then wrench.")
cecho("\n<goldenrod>Damage:")
cecho("\n <green>head <white>              - Used for damage, does not deviate unless target is proned.")
cecho("\n<goldenrod>Limbs:")
cecho("\n <green>ms<white>                 - Used to hit different limbs, will change combo depending on parry.")
elseif snd.class == "Shapeshifter" then
cecho("\n<goldenrod>Damage:")
cecho("\n <green>dmg<white>                - Goes for the head. Each time. Big damage/bleeding if not parried.")
cecho("\n<goldenrod>Limb:")
cecho("\n <green>ms <white>                - Straight limb breaks into jawlocks.")
cecho("\n <green>insta<white>              - Goes for quarter kills. Check AB QUARTER for more information.")
cecho("\n <green>limbs<white>              - Utilizes slash to delay limb breaks, good for pushing level 2 breaks.")
cecho("\n <green>quart<white>              - Better version of insta, use this.")
elseif snd.class == "Infiltrator" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>ms <white>                - Basic dstab w/venoms. No hypnosis.")
cecho("\n <green>magic<white>              - More advanced, geared towards magic, uses hypnosis.")
cecho("\n <green>aff<white>                - More advanced, geared towards physical, uses hypnosis.")
cecho("\n <green>kl<white>                 - 1v1 offense. Does not snap for you as that requires timing.")
cecho("\n<goldenrod>Damage:")
cecho("\n <green>dmg<white>                - Straight damage.")
elseif snd.class == "Wayfarer" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>legs <white>              - Uses lob to pressure leg breaks, will try to dropstrike if able.")
cecho("\n <green>lock<white>               - Experimental skirmish route to seal locks w/slaughter and muddled.")
cecho("\n<goldenrod>Damage:")
cecho("\n <green>dmg<white>                - Sensitivity/sight to support transfix. Boosted halt to keep people in room.")
cecho("\n <green>gaff<white>               - Group affs w/preference toward venom lock. Slaughter if prone w/sensitivity.")
cecho("\n <green>bleed<white>              - Bleed focused to assist Templar w/hemorrhage.")
elseif (snd.class == "Templar" or snd.class == "Revenant") then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>ret <white>               - The 1v1 standard. Lock into retribution.")
cecho("\n <green>newb<white>               - Basic venoms, no bladefire empowerments, no vorpal.")
cecho("\n<goldenrod>Damage:")
cecho("\n <green>dmg<white>                - Use a 2h weapon to zeal/dsw someone and do physical damage.")
cecho("\n <green>bleed<white>              - Bleed focused affs into hemorrhage.")
cecho("\n<goldenrod>Limb:")
cecho("\n <green>limbs<white>              - Two small bludgeon weapons to deal bruising and limb damage.")
elseif snd.class == "Shaman" or snd.class == "Alchemist" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>ms <white>                - Straight vinelash w/venoms.")
cecho("\n <green>storm<white>              - Works toward stormtouched, then goes for lightning damage.")
cecho("\n <green>supp<white>               - Aff-lock support.")
elseif snd.class == "Sentinel" or snd.class == "Executor" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>salve<white>              - Works towards frozen w/limb breaks. Need raloth/icewyrm.")
cecho("\n <green>aff<white>                - Venom lock into spinecut death sequence.")
cecho("\n <green>group<white>              - Group focused small aff pool into spinecut.")
cecho("\n <green>ms<white>                 - Just venoms, no dhuriv attacks, perfect for starters.")
elseif snd.class == "Luminary" or snd.class == "Earthcaller" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>git<white>                - Damage kill with aff stacking and overwhelm.")
cecho("\n <green>mana<white>               - Straight mana sap.")
cecho("\n <green>dmg<white>                - Smite + chasten.")
cecho("\n <green>ms<white>                 - Sight into tfix/overwhelm.")
cecho("\n <green>limbs<white>              - Limb support route")
elseif snd.class == "Ascendril" or snd.class == "Bloodborn" then
cecho("\n<goldenrod>Damage:")
cecho("\n <green>damage<white>             - Damage kill.")
cecho("\n <green>fire<white>               - Set them ablaze and watch them burn.")
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>affs<white>               - Build affs!")
cecho("\n <green>solo<white>               - Push limb damage/frozen for a shatter!")
elseif snd.class == "Zealot" or snd.class == "Ravager" then
cecho("\n<goldenrod>Damage:")
cecho("\n <green>dmg<white>                - Damage kill.")
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>fire<white>               - Focus on ablaze for Zealot support I guess? idk")
elseif snd.class == "Archivist" or snd.class =="Voidseer" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>dmg <white>               - Damage kill")
cecho("\n <green>aff<white>                - Build mental affs and go for unravel")
elseif snd.class == "Carnifex" or snd.class == "Warden" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>dmg <white>               - Damage kill")
cecho("\n <green>aff<white>                - Build affs!")
cecho("\n <green>limbs<white>              - Overall limb route")
cecho("\n <green>legs<white>               - Specifically for legs!")
elseif snd.class == "Indorani" or snd.class == "Oneiromancer" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>dmg <white>               - Damage kill")
cecho("\n <green>aff<white>                - Build affs! High Aeon/Hourglass prio.")
elseif snd.class == "Praenomen" or snd.class == "Akkari" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>dmg <white>               - Damage kill")
cecho("\n <green>aff<white>                - Build affs!")
cecho("\n <green>mez<white>                - Work on siphoning mana for annihilate and mesmerize!")
elseif snd.class == "Teradrim" or snd.class == "Tidesage" then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>dmg <white>               - Damage kill")
cecho("\n <green>aff<white>                - Build affs!")
cecho("\n <green>limbs<white>              - Overall limb route")
elseif snd.class == "Sciomancer" or snd.class == "Runecarver"  then
cecho("\n<goldenrod>Afflictions:")
cecho("\n <green>dmg <white>               - Damage kill")
cecho("\n <green>aff<white>                - Build affs!")
cecho("\n <green>limbs<white>              - Overall limb route via grip and erupt, adds in transfix/chill")
cecho("\n <green>gdmg <white>              - Damage kill with singularity/morass involved")
cecho("\n <green>gaff<white>               - Build affs with singularity/morass involved!")
cecho("\n <green>sing1<white>              - Make your singularity/morass")
cecho("\n <green>gc<white>                 - Shoot your cannon/mortify at your target nearby")
end

cecho("\n<MediumSeaGreen>------------------------------------------")
cecho("\n")
cecho("\n")