cecho("<CadetBlue> Welcome to the <green>Sunder <DeepSkyBlue>Defenses <CadetBlue>help file!")
cecho("\n<MediumSeaGreen>----------------------------------------")
cecho("\n<ForestGreen>Upkeep of defenses can be a tedious task, especially those stripped after a certain amount of time or if you just don't want to worry about it. To that end, Sunder is equipped to be able to help you upkeep defenses in a mildly intelligent manner via checking what skills you have access. The system uses GMCP to automatically check your skills, as well as checking your tattoos and raceskills, to accurately and easily keep track.")
cecho("\n")
cecho("\n<CadetBlue>HOW IT WORKS!")
cecho("\n<MediumSeaGreen>-------------")
cecho("\n")
cecho("\n<CadetBlue>ALIASES")
cecho("\n<MediumSeaGreen>-------")
cecho("\n<DeepSkyBlue>defup                 <ForestGreen>Turn on automatic defense upkeep of defenses.")
cecho("\n<DeepSkyBlue>kd <defname>          <ForestGreen>Toggle a specific defense upkeep on/off.")
cecho("\n")
cecho("\n<green>Sunder<ForestGreen> also has the built in capability to utilize the antiquated artifact goggles, making a number of defs instantaneous and without cost, and antiquated artifacts gauntlets.")
cecho("\n")
cecho("\n<DeepSkyBlue>toggle goggles        <ForestGreen>Toggle Sunder using goggles or not.")
cecho("\n<DeepSkyBlue>mygoggles #           <ForestGreen>Tell Sunder what level your goggles are set to.")
cecho("\n<DeepSkyBlue>mygauntlet #          <ForestGreen>Tell Sunder what level your gauntlet is set to.")
cecho("\n")
cecho("\n<MediumSeaGreen>----------------------------------------")