
snd.global_items = {
-- "a sample of fur and hide",
-- "a dirt sample",
-- "a delicate flora sample",
"a pile of goopy stuffing",
"a roasted hobgobbler drumstick",
}

snd.global_targets = {
--elds
"a warbling hobgobbler",
"a billowing dust eld",
"an oozing magma eld",
"a shifting sand eld",
"a silvery pink salmon",
"a pulsating amber eld",
"a shimmering azure eld",
"a whirling violet eld",
"a shadow-laden grey eld",
"a sinuous eld of rust",
"a vicious crimson eld",
"a vibrating black eld",
"a shimmering azure eld",
"a stalwart iron eld",
"a towering translucent eld",
"a spherical armored eld",
"a dominating frostbound eld",
"a tenebrous ash eld",
"a massive flame-covered eld",
"a jagged citrine eld",
"a crackling lightning eld",
"a crystalline opal eld",
"a crudely formed silver eld",
"an amorphous red eld",
"an immature jade eld",
"a meager golden eld",
"a shattered eld monstrosity",
"a fiery crimson fragmented eld",
"a skittering verdant eld",

--survivor
"a living puppet",
"a sorcerous puppetmaster",
"a fearsome bone dragon",
"a deep purple hydra",
"a monstrous sandman",
"a fearsome wyvern",
"a silver being of flame",
"a towering treant",
"an unctuous creepling",
"a blood-drenched succubus",
"an ethereal construct",
"a black hell-hound",
"a goblin soldier",
"a ravenous, shadowy ghast",
"a warlock apprentice",
"a large, venomous tarantula",
"a massive elemental",
"a muscular mountain lion",
"a skeletal soldier",
"a Troll sentry",
"a mind flayer",
 "a foul-smelling orc",
 "a dwarf guard",
--"a horrendous abomination",
"an enormous black scorpion",
"a Mhun warrior",
"a black cobra",
"a white imp",
"a large reindeer",
"an evil snowman",
"a dark nightmare",

--quests
"a menacing Caentoi cutthroat",
"a grimy bandit",
"a wounded bandit",
"a cutthroat pirate",
"a cutthroat pirate captain",
"a pirate lookout",

--Bloodloch patrols Quest
"a belligerent rebel",
"a freedom fighter",
"an escaped slave",
"a deserter",

--resistance event
"a lithe Utari bladedancer",
"a Tarpen demolitionist",
"an Ursal crossbowman",
"a Praexi skirmisher",
"a towering Golban linebreaker",
"a grim Caentoi pikeman",
}