cecho("\n<CadetBlue>Sunder Helpfile")
cecho("\n<MediumSeaGreen>---------------")
cecho("\n")
cecho("\n<ForestGreen>Welcome to <green>Sunder<ForestGreen>! This helpfile is meant to give you an introduction to different things that <green>Sunder <ForestGreen>can do. It will not cover every option entirely, but it will provide the most often used or asked about items a bit more light to show how or when to use them.")
cecho("\n")
cecho("\n<ForestGreen>The firs thing you should know is the <DeepSkyBlue>?setup <ForestGreen>command. You type <DeepSkyBlue>?setup <ForestGreen>and <green>Sunder <ForestGreen>will run the setup steps. Without this, <green>Sunder <ForestGreen>will not function!")
cecho("\n")
cecho("\n<ForestGreen>The second thing you should know is the <DeepSkyBlue>stap <ForestGreen>command. You type <DeepSkyBlue>stap <ForestGreen>and <green>Sunder <ForestGreen>will cease whatever it is currently attempting to do, for the most part. Some items may need to be toggled manually depending on the situation, but by and large <DeepSkyBlue>stap <ForestGreen>will keep you from hitting someone or something, or any other number of items.")
cecho("\n")
cecho("\n<MediumTurquoise>The index for the rest of the helpfiles is as such:")
cecho("\n")
cecho("\n<DeepSkyBlue>Bashing               <ForestGreen>Do you want to go bashing? <green>Sunder<ForestGreen> has you covered!")
cecho("\n<DeepSkyBlue>PK                    <ForestGreen>Playerkilling and you. Please practice safe PvP.")
cecho("\n<DeepSkyBlue>Defenses              <ForestGreen>How to upkeep, turn on/off and customize defenses.")
cecho("\n<DeepSkyBlue>Ylem                  <ForestGreen>Finding minors and other ylem based information.")
cecho("\n<DeepSkyBlue>Utilities             <ForestGreen>Vermin, fishing, shops, questing and more.")
cecho("\n<DeepSkyBlue>War                   <ForestGreen>Helpful aliases for handling war divisions.")
cecho("\n<DeepSkyBlue>Toggles               <ForestGreen>A list of the available toggles and if they are <DeepSkyBlue>on <ForestGreen>or <SlateGray>off <ForestGreen>.")
cecho("\n<ForestGreen>Each above entry will point you toward more specific items in each section as needed.")
cecho("\n")
cecho("\n<ForestGreen>Use <DeepSkyBlue>sunder help <subject> <ForestGreen>to navigate through everything else.")
cecho("\n")
cecho("\n<MediumSeaGreen>------------------------------------------")
