snd.send("config wrapwidth 0")
snd.send("config outcache on")
snd.send("config combatmessages on")
snd.send("config showafflictions on")
snd.send("config simplediagnose on")
snd.send("config curingtype default")
snd.send("config fishgraphic off")
snd.send("config badcommand off")
snd.send("gathering on")
npb.init()