snd.afflictions = {
  aff_health_75                  = { state = "healed", cures = { elixir = "health" }, assess = false, timer = createStopWatch() },
  aff_health_55                  = { state = "healed", cures = { elixir = "health" }, assess = false, timer = createStopWatch() },
  aff_health_35                  = { state = "healed", cures = { elixir = "health" }, assess = false, timer = createStopWatch() },
  aff_health_10                  = { state = "healed", cures = { elixir = "health" }, assess = false, timer = createStopWatch() },
  aff_mana_75                    = { state = "healed", cures = { elixir = "mana" }, assess = false, timer = createStopWatch() },
  aff_mana_55                    = { state = "healed", cures = { elixir = "mana" }, assess = false, timer = createStopWatch() },
  aff_mana_35                    = { state = "healed", cures = { elixir = "mana" }, assess = false, timer = createStopWatch() },
  aff_mana_35                    = { state = "healed", cures = { elixir = "mana" }, assess = false, timer = createStopWatch() },
  aff_mana_10                    = { state = "healed", cures = { elixir = "mana" }, assess = false, timer = createStopWatch() },
  aff_health_low                 = { state = "healed", cures = { moss = "send" }, assess = false, timer = createStopWatch() },
  aff_mana_low                   = { state = "healed", cures = { moss = "send" }, assess = false, timer = createStopWatch() },
  aff_bleeding                   = { state = "healed", cures = { clot = "send" }, assess = false, timer = createStopWatch() },

  aff_oblivion                   = { state = "healed", effect = "Death unless you interrupt the bard", cures = {}, assess = false, timer = createStopWatch() },

  aff_shock                      = { state = "healed", effect = "less mobility", cures = {}, assess = false, timer = createStopWatch() },
  aff_burnout                    = { state = "healed", effect = "slower cds", cures = {}, assess = false, timer = createStopWatch() },

  aff_prone                      = { state = "healed", effect = "cannot move or attack, must STAND", cures = { stand = "send" }, assess = false, timer = createStopWatch() },
  aff_asleep                     = { state = "healed", effect = "cannot do anything other than WAKE", cures = {}, assess = false, timer = createStopWatch() },
  aff_stun                       = { state = "healed", effect = "cannot do anything", cures = {}, assess = false, timer = createStopWatch() },
  aff_aeon                       = { state = "healed", effect = "delays all actions", cures = { smoke = "elm" }, assess = false, timer = createStopWatch() },

  aff_paresis                    = { state = "healed", effect = "prevents tattoos and movement", cures = { herb = "bloodroot" }, assess = false, timer = createStopWatch() },
  aff_paralysis                  = { state = "healed", effect = "prevents attacks, movement, and tattoos", cures = { herb = "bloodroot" }, assess = false, timer = createStopWatch() },
  aff_anorexia                   = { state = "healed", effect = "prevents eating", cures = { tree = "send", salve = "epidermal to torso", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_asthma                     = { state = "healed", effect = "prevents smoking", cures = { tree = "send", herb = "kelp" }, assess = false, timer = createStopWatch() },
  aff_slickness                  = { state = "healed", effect = "prevents applying salves", cures = { tree = "send", smoke = "valerian", herb = "bloodroot" }, assess = false, timer = createStopWatch() },

  aff_crippled_arm               = { state = "healed", effect = "", cures = { salve = "mending to arms", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_crippled_leg               = { state = "healed", effect = "", cures = { salve = "mending to legs", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_adder_tarot                = { state = "healed", effect = "", cures = { balanceequilibrium = "rip card from body" }, assess = false, timer = createStopWatch() },

  aff_ablaze                     = { state = "healed", effect = "", cures = { salve = "mending to body", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_accursed                   = { state = "healed", effect = "", cures = { herb = "bellwort", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_achromatopsia              = { state = "healed", effect = "colors leeched away", cures = {}, assess = false, timer = createStopWatch() },
  aff_addiction                  = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_aftershock                 = { state = "healed", effect = "gain affs if earthcaller seismicity hits you", cures = {}, assess = false, timer = createStopWatch() },
  aff_agony                      = { state = "healed", effect = "", cures = { herb = "bellwort", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_agoraphobia                = { state = "healed", effect = "", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_allergies                  = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_amplify_asphyxiation       = { state = "healed", effect = "more dmg from asphyx source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_blunt              = { state = "healed", effect = "more dmg from blunt source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_cold               = { state = "healed", effect = "more dmg from cold source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_cutting            = { state = "healed", effect = "more dmg from cutting source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_electric           = { state = "healed", effect = "more dmg from electric source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_fire               = { state = "healed", effect = "more dmg from fire source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_magic              = { state = "healed", effect = "more dmg from magic source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_poison             = { state = "healed", effect = "more dmg from poison source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_psychic            = { state = "healed", effect = "more dmg from psychic source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_shadow             = { state = "healed", effect = "more dmg from shadow source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_spirit             = { state = "healed", effect = "more dmg from spirit source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_amplify_unblockable        = { state = "healed", effect = "more dmg from unblockable source per stack", cures = {}, assess = false, timer = createStopWatch() },
  aff_airwreath                  = { state = "healed", effect = "dmg over time", cures = {}, assess = false, timer = createStopWatch() },
  aff_arrow_wound                = { state = "healed", effect = "delayed by stacks of arrows", cures = {}, assess = false, timer = createStopWatch() },
  aff_asphyxiation_weakness      = { state = "healed", effect = "more dmg from asphyx source", cures = {}, assess = false, timer = createStopWatch() },
  aff_asterism                   = { state = "healed", effect = "anomaly", cures = {}, assess = false, timer = createStopWatch() },
  aff_atrophy                    = { state = "healed", effect = "half damage except against giver of affliction", cures = {}, assess = false, timer = createStopWatch() },
  aff_attuned                    = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_backstabbed                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_backstrain                 = { state = "healed", effect = "torso dmg on standing", cures = { tree = "send", salve = "soothing to torso" }, assess = false, timer = createStopWatch() },
  aff_barbs                      = { state = "healed", effect = "dmg per stack of barbs", cures = { balanceequilibrium = "pull barbs from body" }, assess = false, timer = createStopWatch() },
  aff_battle_hunger              = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_besilence                  = { state = "healed", effect = "stops some actions", cures = { smoke = "reishi" }, assess = false, timer = createStopWatch() },
  aff_berserking                 = { state = "healed", effect = "", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_blackout                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_blighted                   = { state = "healed", effect = "", cures = { herb = "ash", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_blisters                   = { state = "healed", effect = "poison dmg/bleeding when using bal/eq", cures = { tree = "send", herb = "bloodroot" }, assess = false, timer = createStopWatch() },
  aff_blood_curse                = { state = "healed", effect = "", cures = { herb = "ash", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_blood_poison               = { state = "healed", effect = "", cures = { herb = "kelp", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_bloodlust                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_blunt_weakness             = { state = "healed", effect = "more dmg from blunt source", cures = {}, assess = false, timer = createStopWatch() },
  aff_blurry_vision              = { state = "healed", effect = "", cures = { salve = "epidermal to body", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_bulimia                    = { state = "healed", effect = "vomit the next thing you eat", cures = {}, assess = false, timer = createStopWatch() },
  aff_burnt_eyes                 = { state = "healed", effect = "", cures = { salve = "epidermal to head", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_burnt_skin                 = { state = "healed", effect = "", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_chaos_warp                 = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_claustrophobia             = { state = "healed", effect = "", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_clumsiness                 = { state = "healed", effect = "", cures = { herb = "kelp", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_cold_weakness              = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_collapsed_lung             = { state = "healed", effect = "", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_confusion                  = { state = "healed", effect = "", cures = { herb = "ash", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_conviction                 = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_corsin_weight              = { state = "healed", effect = "One celery", cures = {}, assess = false, timer = createStopWatch() },
  aff_cracked_ribs               = { state = "healed", effect = "", cures = { salve = "mending to torso", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_crippled                   = { state = "healed", effect = "", cures = { herb = "bloodroot", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_crippled_body              = { state = "healed", effect = "", cures = { herb = "bloodroot", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_crippled_throat            = { state = "healed", effect = "", cures = { salve = "mending to head", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_crushed_chest              = { state = "healed", effect = "", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_crushed_elbows             = { state = "healed", effect = "", cures = { salve = "mending to arms", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_crushed_kneecaps           = { state = "healed", effect = "", cures = { salve = "mending to legs", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_cutting_weakness           = { state = "healed", effect = "more dmg from cuttingsource", cures = {}, assess = false, timer = createStopWatch() },
  aff_dazed                      = { state = "healed", effect = "can't regain balance normally", cures = { balanceequilibrium = "recoup" }, assess = false, timer = createStopWatch() },
  aff_deadening                  = { state = "healed", effect = "", cures = { smoke = "elm", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_deepwound                  = { state = "healed", effect = "makes bleeding more impactful (cant clot immediately)", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_dementia                   = { state = "healed", effect = "", cures = { herb = "ash", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_despair                    = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_destroyed_throat           = { state = "healed", effect = "", cures = { salve = "mending to head", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_direfrost                  = { state = "healed", effect = "leads to frostbrand", cures = {}, assess = false, timer = createStopWatch() },
  aff_disabled                   = { state = "healed", effect = "divine only? unsure", cures = {}, assess = false, timer = createStopWatch() },
  aff_disfigurement              = { state = "healed", effect = "", cures = { smoke = "valerian", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_disorientated              = { state = "healed", effect = "delays cures by 1.5 seconds", cures = {}, assess = false, timer = createStopWatch() },
  aff_disrupted                  = { state = "healed", effect = "", cures = { special = "concentrate" }, assess = false, timer = createStopWatch() },
  aff_dissonance                 = { state = "healed", effect = "", cures = { herb = "goldenseal", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_distortion                 = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_dizziness                  = { state = "healed", effect = "", cures = { herb = "goldenseal", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_dustring                   = { state = "healed", effect = "anomaly", cures = {}, assess = false, timer = createStopWatch() },
  aff_effused_blood              = { state = "healed", effect = "", cures = { salve = "epidermal to torso" }, assess = false, timer = createStopWatch() },
  aff_eldritch_invocation        = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_electric_weakness          = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_echoes                     = { state = "healed", effect = "", cures = { herb = "eucrasia" }, assess = false, timer = createStopWatch() },
  aff_emberbrand                 = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_egocentric                 = { state = "healed", effect = "can't help others", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_embedded_axe               = { state = "healed", effect = "does major limb damage when pulled", cures = { balanceequilibrium = "pull axe from me" }, assess = false, timer = createStopWatch() },
  aff_epilepsy                   = { state = "healed", effect = "", cures = { herb = "goldenseal", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_exhausted                  = { state = "healed", effect = "dodge cut in half, slower movement", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_farag_rot                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_faintness                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_fear                       = { state = "healed", effect = "", cures = { special = "compose" }, assess = false, timer = createStopWatch() },
  aff_fire_weakness              = { state = "healed", effect = "more dmg from fire source", cures = {}, assess = false, timer = createStopWatch() },
  aff_flamewreathed_limb         = { state = "healed", effect = "extra limb damage if hit by fire spell", cures = {}, assess = false, timer = createStopWatch() },
  aff_flared                     = { state = "healed", effect = "unable to stealth or go incorporeal", cures = {}, assess = false, timer = createStopWatch() },
  aff_flash_blindness            = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_forestbrand                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_frigid                     = { state = "healed", effect = "Delayed movement", cures = { salve = "caloric to torso", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_frostbrand                 = { state = "healed", effect = "continually freezes over time", cures = {}, assess = false, timer = createStopWatch() },
  aff_frostwreath                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_frozen                     = { state = "healed", effect = "Stops movement", cures = { salve = "caloric to torso", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_frozen_feet                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_glasslimb                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_gloom                      = { state = "healed", effect = "", cures = { salve = "epidermal to head" }, assess = false, timer = createStopWatch() },
  aff_gnawing                    = { state = "healed", effect = "lowers constitution by 2", cures = { salve = "epidermal to torso" }, assess = false, timer = createStopWatch() },
  aff_gorged                     = { state = "healed", effect = "", cures = { salve = "epidermal to head", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_haemophilia                = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_hallucinations             = { state = "healed", effect = "", cures = { herb = "ash", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_hatred                     = { state = "healed", effect = "", cures = { herb = "ash", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_head_crippled              = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_head_bruised               = { state = "healed", effect = "", cures = { salve = "mending to head" }, assess = false, timer = createStopWatch() },
  aff_head_bruised_critical      = { state = "healed", effect = "", cures = { salve = "mending to head" }, assess = false, timer = createStopWatch() },
  aff_head_bruised_moderate      = { state = "healed", effect = "", cures = { salve = "mending  to head" }, assess = false, timer = createStopWatch() },
  aff_head_broken                = { state = "healed", effect = "", cures = { salve = "restoration to head" }, assess = false, timer = createStopWatch() },
  aff_head_mangled               = { state = "healed", effect = "", cures = { salve = "restoration to head" }, assess = false, timer = createStopWatch() },
  aff_head_ravaged               = { state = "healed", effect = "not sure it's actually used since ravage is untargetted now", cures = {}, assess = false, timer = createStopWatch() },
  aff_heartflutter               = { state = "healed", effect = "", cures = { herb = "bloodroot", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_hellsight                  = { state = "healed", effect = "", cures = { smoke = "elm", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_heatspear                  = { state = "healed", effect = "can't cure ablaze", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_hollow                     = { state = "healed", effect = "mana drain + aff if alone", cures = { herb = "eucrasia", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_hubris                     = { state = "healed", effect = "", cures = { herb = "bellwort", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_hypersomnia                = { state = "healed", effect = "", cures = { herb = "ash", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_hypertension               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_hypochondria               = { state = "healed", effect = "", cures = { herb = "kelp", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_hypothermia                = { state = "healed", effect = "", cures = { salve = "epidermal to torso", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_idiocy                     = { state = "healed", effect = "", cures = { moss = "send", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_impeded                    = { state = "healed", effect = "10% slower pills, cured by removing gravity", cures = {}, assess = false, timer = createStopWatch() },
  aff_impairment                 = { state = "healed", effect = "longer stuns, no racials", cures = { herb = "decongestant" }, assess = false, timer = createStopWatch() },
  aff_plodding                   = { state = "healed", effect = "", cures = { moss = "send", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_ice_encased                = { state = "healed", effect = "longer salve bal, extra blunt dmg", cures = {}, assess = false, timer = createStopWatch() },
  aff_illgrasp                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_imbued                     = { state = "healed", effect = "auto gravity from scio spells", cures = {}, assess = false, timer = createStopWatch() },
  aff_impatience                 = { state = "healed", effect = "", cures = { herb = "goldenseal", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_indifference               = { state = "healed", effect = "", cures = { salve = "epidermal to head", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_infernal_seal              = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_infernal_shroud            = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_infested                   = { state = "healed", effect = "", cures = { herb = "goldenseal", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_insomnia                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_irradiated_limb            = { state = "healed", effect = "more damage from bolt", cures = {}, assess = false, timer = createStopWatch() },
  aff_itchy                      = { state = "healed", effect = "tree has to cure this first always", cures = { tree = "send" }, assess = false, timer = createStopWatch() },
  aff_intimidated                = { state = "healed", effect = "can't heal above 90%", cures = {}, assess = false, timer = createStopWatch() },
  aff_justice                    = { state = "healed", effect = "", cures = { herb = "bellwort", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_laxity                     = { state = "healed", effect = "", cures = { herb = "bellwort", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_leeched_aura               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_left_arm_amputated         = { state = "healed", effect = "", cures = { salve = "restoration to arms" }, assess = false, timer = createStopWatch() },
  aff_left_arm_crippled          = { state = "healed", effect = "", cures = { salve = "mending to arms", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_left_arm_bruised           = { state = "healed", effect = "", cures = { salve = "mending to arms" }, assess = false, timer = createStopWatch() },
  aff_left_arm_bruised_critical  = { state = "healed", effect = "", cures = { salve = "mending to arms" }, assess = false, timer = createStopWatch() },
  aff_left_arm_bruised_moderate  = { state = "healed", effect = "", cures = { salve = "mending to arms" }, assess = false, timer = createStopWatch() },
  aff_left_arm_broken            = { state = "healed", effect = "", cures = { salve = "restoration to arms" }, assess = false, timer = createStopWatch() },
  aff_left_arm_dislocated        = { state = "healed", effect = "", cures = { salve = "mending to arms" }, assess = false, timer = createStopWatch() },
  aff_left_arm_mangled           = { state = "healed", effect = "", cures = { salve = "restoration to arms" }, assess = false, timer = createStopWatch() },
  aff_left_arm_numbed            = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_left_arm_ravaged           = { state = "healed", effect = "not sure it's actually used since ravage is untargetted now", cures = {}, assess = false, timer = createStopWatch() },
  aff_left_leg_amputated         = { state = "healed", effect = "", cures = { salve = "restoration to legs" }, assess = false, timer = createStopWatch() },
  aff_left_leg_crippled          = { state = "healed", effect = "", cures = { salve = "mending to legs", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_left_leg_bruised           = { state = "healed", effect = "", cures = { salve = "mending to legs" }, assess = false, timer = createStopWatch() },
  aff_left_leg_bruised_critical  = { state = "healed", effect = "", cures = { salve = "mending to legs" }, assess = false, timer = createStopWatch() },
  aff_left_leg_bruised_moderate  = { state = "healed", effect = "", cures = { salve = "mending to legs" }, assess = false, timer = createStopWatch() },
  aff_left_leg_broken            = { state = "healed", effect = "", cures = { salve = "restoration to legs" }, assess = false, timer = createStopWatch() },
  aff_left_leg_dislocated        = { state = "healed", effect = "", cures = { salve = "mending to legs" }, assess = false, timer = createStopWatch() },
  aff_left_leg_mangled           = { state = "healed", effect = "", cures = { salve = "restoration to legs" }, assess = false, timer = createStopWatch() },
  aff_left_leg_numbed            = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_left_leg_ravaged           = { state = "healed", effect = "not sure it's actually used since ravage is untargetted now", cures = {}, assess = false, timer = createStopWatch() },
  aff_lesser_atrophy             = { state = "healed", effect = "do less damage", cures = {}, timer = createStopWatch() },
  aff_lemniscate                 = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_lethargy                   = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_lifebane                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_lightwound                 = { state = "healed", effect = "extra bleeding", cures = { salve = "mending to body" }, assess = false, timer = createStopWatch() },
  aff_limp_veins                 = { state = "healed", effect = "", cures = { herb = "kelp", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_loneliness                 = { state = "healed", effect = "", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_lovers_effect              = { state = "healed", effect = "", cures = { herb = "bellwort", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_magic_fire                 = { state = "healed", effect = "ablaze mask aff", cures = { salve = "mending" }, assess = false, timer = createStopWatch() },
  aff_magic_weakness             = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_magnanimity                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_malevolence                = { state = "healed", effect = "destroys shield, extra damage from weather", cures = {}, assess = false, timer = createStopWatch() },
  aff_manablight                 = { state = "healed", effect = "mana loss on torso hit", cures = { salve = "epidermal to torso" }, assess = false, timer = createStopWatch() },
  aff_marked                     = { state = "healed", effect = "marked by a mage", cures = {}, assess = false, timer = createStopWatch() },
  aff_masochism                  = { state = "healed", effect = "", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_mauled_face                = { state = "healed", effect = "", cures = { salve = "restoration to head" }, assess = false, timer = createStopWatch() },
  aff_mental_disruption          = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_mental_fatigue             = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_merciful                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_migraine                   = { state = "healed", effect = "", cures = { smoke = "valerian", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_turmoil                    = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_mind_clamped               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_mirroring                  = { state = "healed", effect = "", cures = { herb = "bloodroot", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_misery                     = { state = "healed", effect = "messes with resist aff defenses", cures = { herb = "eucrasia", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_mistbrand                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_moonlet                    = { state = "healed", effect = "anomaly", cures = {}, assess = false, timer = createStopWatch() },
  aff_muddled                    = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_muscle_spasms              = { state = "healed", effect = "chance to apply incorrectly", cures = { tree = "send", salve = "soothing to torso" }, assess = false, timer = createStopWatch() },
  aff_mutagen                    = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_mutation_sickness          = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_narcolepsy                 = { state = "healed", effect = "makes you try to sleep every 6 sec", cures = { herb = "eucrasia", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_nightmare                  = { state = "healed", effect = "???", cures = {}, assess = false, timer = createStopWatch() },
  aff_nyctophobia                = { state = "healed", effect = "can't move in to/out of darkness", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_numb_arms                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_numbed_skin                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_oiled                      = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_omen                       = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_paranoia                   = { state = "healed", effect = "", cures = { herb = "ash", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_patterns                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_peace                      = { state = "healed", effect = "", cures = { herb = "bellwort", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_penance                    = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_perplexed                  = { state = "healed", effect = "can't manipulate items", cures = { herb = "eucrasia", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_petrified                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_physical_disruption        = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_polymorph                  = { state = "healed", effect = "divine only? unsure", cures = {}, assess = false, timer = createStopWatch() },
  aff_poison_weakness            = { state = "healed", effect = "more dmg from poison source", cures = {}, assess = false, timer = createStopWatch() },
  aff_pre_restore_head           = { state = "healed", effect = "", cures = { salve = "restoration to head" }, assess = false, timer = createStopWatch() },
  aff_pre_restore_left_arm       = { state = "healed", effect = "", cures = { salve = "restoration to arms" }, assess = false, timer = createStopWatch() },
  aff_pre_restore_left_leg       = { state = "healed", effect = "", cures = { salve = "restoration to legs" }, assess = false, timer = createStopWatch() },
  aff_pre_restore_right_arm      = { state = "healed", effect = "", cures = { salve = "restoration to right arm" }, assess = false, timer = createStopWatch() },
  aff_pre_restore_right_leg      = { state = "healed", effect = "", cures = { salve = "restoration to right leg" }, assess = false, timer = createStopWatch() },
  aff_pre_restore_torso          = { state = "healed", effect = "", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_premonition                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_pressured                  = { state = "healed", effect = "?", cures = {}, assess = false, timer = createStopWatch() },
  aff_psi_tether                 = { state = "healed", effect = "hurts you if you walk too far from zealot", cures = {}, assess = false, timer = createStopWatch() },
  aff_psychic_weakness           = { state = "healed", effect = "more dmg from psychic source", cures = {}, assess = false, timer = createStopWatch() },
  aff_punished_arms              = { state = "healed", effect = "unable to parry", cures = {}, assess = false, timer = createStopWatch() },
  aff_punished_legs              = { state = "healed", effect = "movement has 33% chance to fail", cures = {}, assess = false, timer = createStopWatch() },
  aff_quicksand                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_undertow                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_ravaged                    = { state = "healed", effect = "applying salves hurts you", cures = {}, assess = false, timer = createStopWatch() },
  aff_recklessness               = { state = "healed", effect = "", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_rend                       = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_resin_glauxe               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_resonance                  = { state = "healed", effect = "templar can assess/diagnose you for free", cures = {}, assess = false, timer = createStopWatch() },
  aff_right_arm_amputated        = { state = "healed", effect = "", cures = { salve = "restoration to right arm" }, assess = false, timer = createStopWatch() },
  aff_right_arm_crippled         = { state = "healed", effect = "", cures = { salve = "mending to arms", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_right_arm_bruised          = { state = "healed", effect = "", cures = { salve = "mending to arms" }, assess = false, timer = createStopWatch() },
  aff_right_arm_bruised_critical = { state = "healed", effect = "", cures = { salve = "mending to arms" }, assess = false, timer = createStopWatch() },
  aff_right_arm_bruised_moderate = { state = "healed", effect = "", cures = { salve = "mending to arms" }, assess = false, timer = createStopWatch() },
  aff_right_arm_broken           = { state = "healed", effect = "", cures = { salve = "restoration to right arm" }, assess = false, timer = createStopWatch() },
  aff_right_arm_dislocated       = { state = "healed", effect = "", cures = { salve = "mending to arms" }, assess = false, timer = createStopWatch() },
  aff_right_arm_mangled          = { state = "healed", effect = "", cures = { salve = "restoration to right arm" }, assess = false, timer = createStopWatch() },
  aff_right_arm_numbed           = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_right_arm_ravaged          = { state = "healed", effect = "not sure it's actually used since ravage is untargetted now", cures = {}, assess = false, timer = createStopWatch() },
  aff_right_leg_amputated        = { state = "healed", effect = "", cures = { salve = "restoration to right leg" }, assess = false, timer = createStopWatch() },
  aff_right_leg_crippled         = { state = "healed", effect = "", cures = { salve = "mending to legs", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_right_leg_bruised          = { state = "healed", effect = "", cures = { salve = "mending to legs" }, assess = false, timer = createStopWatch() },
  aff_right_leg_bruised_critical = { state = "healed", effect = "", cures = { salve = "mending to legs" }, assess = false, timer = createStopWatch() },
  aff_right_leg_bruised_moderate = { state = "healed", effect = "", cures = { salve = "mending to legs" }, assess = false, timer = createStopWatch() },
  aff_right_leg_broken           = { state = "healed", effect = "", cures = { salve = "restoration to right leg" }, assess = false, timer = createStopWatch() },
  aff_right_leg_dislocated       = { state = "healed", effect = "", cures = { salve = "mending to legs" }, assess = false, timer = createStopWatch() },
  aff_right_leg_mangled          = { state = "healed", effect = "", cures = { salve = "restoration to right leg" }, assess = false, timer = createStopWatch() },
  aff_right_leg_numbed           = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_right_leg_ravaged          = { state = "healed", effect = "not sure it's actually used since ravage is untargetted now", cures = {}, assess = false, timer = createStopWatch() },
  aff_ringing_ears               = { state = "healed", effect = "unable to become deaf until cured", cures = { herb = "lobelia", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_ripped_groin               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_ripped_spleen              = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_ripped_throat              = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_ruptured_eardrum           = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sadness                    = { state = "healed", effect = "", cures = { herb = "ash", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_salve_seared               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sand_trapped               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_fog_trapped                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_slough                     = { state = "healed", effect = "", cures = { herb = "bloodroot", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_sapped_constitution        = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sapped_dexterity           = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sapped_intelligence        = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sapped_stats               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sapped_strength            = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sapped_wisdom              = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sealing_circle             = { state = "healed", effect = "circle affs cant be cured by pill", cures = {}, assess = false, timer = createStopWatch() },
  aff_sealing_square             = { state = "healed", effect = "square affs cant be cured by pill", cures = {}, assess = false, timer = createStopWatch() },
  aff_sealing_triangle           = { state = "healed", effect = "triangle affs cant be cured by pill", cures = {}, assess = false, timer = createStopWatch() },
  aff_selarnia                   = { state = "healed", effect = "", cures = { salve = "mending to torso", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_self_loathing              = { state = "healed", effect = "5s bal knock if left on for 12s", cures = { herb = "eucrasia", tree = "send" }, assess = false, timer = createStopWatch() },
  ["aff_self-pity"]              = { state = "healed", effect = "", cures = { herb = "goldenseal", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_seduction                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_sensitivity                = { state = "healed", effect = "", cures = { herb = "kelp", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_stoneheld                  = { state = "healed", effect = "Can't move", cures = {}, assess = false, timer = createStopWatch() },
  aff_rot_benign                 = { state = "healed", effect = "shaderot1 - no affs", cures = { herb = "panacea" }, assess = false, timer = createStopWatch() },
  aff_rot_body                   = { state = "healed", effect = "shaderot5 - salve recovery doubled", cures = { herb = "panacea" }, assess = false, timer = createStopWatch() },
  aff_rot_heat                   = { state = "healed", effect = "shaderot3 - can't apply caloric", cures = { herb = "panacea" }, assess = false, timer = createStopWatch() },
  aff_rot_spirit                 = { state = "healed", effect = "shaderot2 - shadow damage", cures = { herb = "panacea" }, assess = false, timer = createStopWatch() },
  aff_rot_wither                 = { state = "healed", effect = "shaderot4 - passive lethargy", cures = { herb = "panacea" }, assess = false, timer = createStopWatch() },
  aff_shadow_coat                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_shadow_weakness            = { state = "healed", effect = "more dmg from shadow source", cures = {}, assess = false, timer = createStopWatch() },
  aff_shadowbrand                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_shadowed                   = { state = "healed", effect = "gain affs if luminary shine hits you", cures = {}, assess = false, timer = createStopWatch() },
  aff_shadowsphere               = { state = "healed", effect = "hides scio affs and generally a bad time", cures = {}, assess = false, timer = createStopWatch() },
  aff_shivering                  = { state = "healed", effect = "", cures = { salve = "caloric", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_shyness                    = { state = "healed", effect = "", cures = { herb = "goldenseal", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_slough                     = { state = "healed", effect = "no salves", cures = { herb = "bloodroot", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_smashed_throat             = { state = "healed", effect = "", cures = { salve = "restoration to head" }, assess = false, timer = createStopWatch() },
  aff_sore_ankle                 = { state = "healed", effect = "leg dmg on movement", cures = { tree = "send", salve = "soothing to legs" }, assess = false, timer = createStopWatch() },
  aff_sore_wrist                 = { state = "healed", effect = "arm dmg on parry", cures = { tree = "send", salve = "soothing to arms" }, assess = false, timer = createStopWatch() },
  aff_soul_disease               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_soul_poison                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_soulchill                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_soulpuncture               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_soulroot                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_spinal_rip                 = { state = "healed", effect = "", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_spiritbane                 = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_spiritbrand                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_spirit_weakness            = { state = "healed", effect = "more dmg from spirit source", cures = {}, assess = false, timer = createStopWatch() },
  aff_squelched                  = { state = "healed", effect = "", cures = { smoke = "valerian", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_stiffness                  = { state = "healed", effect = "lower dodge/divert, soothing cured affs can break bones", cures = { tree = "send", salve = "soothing to torso" }, assess = false, timer = createStopWatch() },
  aff_stonebrand                 = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_stonevice                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_stormtouched               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_stupidity                  = { state = "healed", effect = "", cures = { herb = "goldenseal", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_stuttering                 = { state = "healed", effect = "", cures = { salve = "epidermal to head", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_superstition               = { state = "healed", effect = "", cures = { herb = "bellwort", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_temptation                 = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_taunted                    = { state = "healed", effect = "can only hit who taunted you", cures = {}, assess = false, timer = createStopWatch() },
  aff_terror                     = { state = "healed", effect = "prevents ability to compose", cures = {}, assess = false, timer = createStopWatch() },
  aff_thin_blood                 = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_thorns                     = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_throatclaw                 = { state = "healed", effect = "", cures = { salve = "mending to head", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_throatslice                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_thunderstorm               = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_torso_bruised              = { state = "healed", effect = "", cures = { salve = "mending to torso" }, assess = false, timer = createStopWatch() },
  aff_torso_bruised_critical     = { state = "healed", effect = "", cures = { salve = "mending to torso" }, assess = false, timer = createStopWatch() },
  aff_torso_bruised_moderate     = { state = "healed", effect = "", cures = { salve = "mending to torso" }, assess = false, timer = createStopWatch() },
  aff_torso_broken               = { state = "healed", effect = "", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_torso_mangled              = { state = "healed", effect = "", cures = { salve = "restoration to torso" }, assess = false, timer = createStopWatch() },
  aff_torso_ravaged              = { state = "healed", effect = "not sure it's actually used since ravage is untargetted now", cures = {}, assess = false, timer = createStopWatch() },
  aff_tree_seared                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_trick_flame                = { state = "healed", effect = "doubles ablaze stacks, easier re-application of stacks", cures = {}, assess = false, timer = createStopWatch() },
  aff_troubled_breathing         = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_vertigo                    = { state = "healed", effect = "", cures = { herb = "lobelia", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_vinethorns                 = { state = "healed", effect = "", cures = { special = "pull thorn from body" }, assess = false, timer = createStopWatch() },
  aff_vitalbane                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_void                       = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_voidgaze                   = { state = "healed", effect = "gives stacking affs while active", cures = { salve = "restoration to head" }, assess = false, timer = createStopWatch() },
  aff_voidtrapped                = { state = "healed", effect = "stuck prone for a bit via voidgaze", cures = {}, assess = false, timer = createStopWatch() },
  aff_vomiting                   = { state = "healed", effect = "", cures = { herb = "ginseng", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_voyria                     = { state = "healed", effect = "", cures = { vial = "immunity" }, assess = false, timer = createStopWatch() },
  aff_weak_grip                  = { state = "healed", effect = "bypass fist sigil", cures = { tree = "send", salve = "soothing to arms" }, assess = false, timer = createStopWatch() },
  aff_weakvoid                   = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_whiplash                   = { state = "healed", effect = "head dmg", cures = { tree = "send", salve = "soothing to legs" }, assess = false, timer = createStopWatch() },
  aff_winterheart                = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_weariness                  = { state = "healed", effect = "", cures = { herb = "kelp", tree = "send", focus = "send" }, assess = false, timer = createStopWatch() },
  aff_windbrand                  = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_withering                  = { state = "healed", effect = "", cures = { smoke = "elm", tree = "send" }, assess = false, timer = createStopWatch() },
  aff_wraith                     = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_writhe_armpitlock          = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_bind                = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_hoist               = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_impaled             = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_lure                = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_necklock            = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_ropes               = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_gunk                = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_thighlock           = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_transfix            = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_vines               = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_web                 = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_grappled            = { state = "healed", effect = "", cures = { writhe = "send" }, assess = false, timer = createStopWatch() },
  aff_writhe_stasis              = { state = "healed", effect = "can't move, can attack", cures = {}, assess = false, timer = createStopWatch() },
  aff_writhe_ice                 = { state = "healed", effect = "brrrr", cures = {}, assess = false, timer = createStopWatch() },

  aff_awakened                   = { state = "healed", effect = "Some bard nonsense", cures = {}, assess = false, timer = createStopWatch() },

  --ravager thing
  aff_kneel                      = { state = "healed", effect = "hurts you if you walk too far from ravager", cures = {}, assess = false, timer = createStopWatch() },

  --predator
  aff_bloodscourge               = { state = "healed", effect = "", cures = { smoke = "todisplay" }, assess = false, timer = createStopWatch() },
  aff_embedded_dagger            = { state = "healed", effect = "", cures = { smoke = "todisplay" }, assess = false, timer = createStopWatch() },
  aff_fleshbane                  = { state = "healed", effect = "", cures = { smoke = "todisplay" }, assess = false, timer = createStopWatch() },
  aff_goaded                     = { state = "healed", effect = "", cures = { smoke = "todisplay" }, assess = false, timer = createStopWatch() },
  aff_intoxicated                = { state = "healed", effect = "", cures = { smoke = "todisplay" }, assess = false, timer = createStopWatch() },
  aff_writhe_dartpinned          = { state = "healed", effect = "", cures = { smoke = "todisplay" }, assess = false, timer = createStopWatch() },

  ---- Mirror affs here
  --Voidseer
  aff_etched_disgust             = { state = "healed", effect = "circle affs cant be cured by pill", cures = {}, assess = false, timer = createStopWatch() },
  aff_etched_fear                = { state = "healed", effect = "square affs cant be cured by pill", cures = {}, assess = false, timer = createStopWatch() },
  aff_etched_joy                 = { state = "healed", effect = "triangle affs cant be cured by pill", cures = {}, assess = false, timer = createStopWatch() },
  aff_sonder                     = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },

  --Executor
  aff_coagulated_toxins          = { state = "healed", effect = "One celery", cures = {}, assess = false, timer = createStopWatch() },


  --Revenant
  aff_lurk = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_mortalterror = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },

  --Oneiromancer
  aff_fae_curse = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_unspooled = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },

  --Warden
  aff_ancestral_portent = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_ancestral_ambush = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_haunting = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_eluded = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_debilitated = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_inhibited = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },

  --Earthcaller
  aff_faulted = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },

  --octopus
  aff_acidic_ink = { state = "healed", effect = "It's ink. You wait it out.", cures = {}, assess = false, timer = createStopWatch() },

  --Bloodborn
  aff_excess_choleric = { state = "healed", effect = "emberbrand - ablaze on all spells", cures = {}, assess = false, timer = createStopWatch() },
  aff_excess_melancholic = { state = "healed", effect = "thunderbrand - health damage, slower pills", cures = {}, assess = false, timer = createStopWatch() },
  aff_frostbite = { state = "healed", effect = "leads to frostbrand", cures = {}, assess = false, timer = createStopWatch() },
  aff_excess_phlegm = { state = "healed", effect = "frostbrand - continually freezes over time", cures = {}, assess = false, timer = createStopWatch() },
  aff_corroded_limb = { state = "healed", effect = "extra limb damage if hit by yellowbile spell", cures = {}, assess = false, timer = createStopWatch() },
  aff_bile_covered = { state = "healed", effect = "dmg over time", cures = {}, assess = false, timer = createStopWatch() },
  aff_phlegm_frozen = { state = "healed", effect = "gives an additional cold damage proc on cold damage receive", cures = {}, assess = false, timer = createStopWatch() },
  aff_etherflux = { state = "healed", effect = "50% chance of elemental damage to cause other things", cures = { vial = "infusion" }, assess = false, timer = createStopWatch() },



  --Runecarver
  aff_inoculated = { state = "healed", effect = "auto gravity from scio spells", cures = {}, assess = false, timer = createStopWatch() },
  aff_fungal_invasion = { state = "healed", effect = "10% slower pills, cured by removing gravity", cures = {}, assess = false, timer = createStopWatch() },
  aff_preymark = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_woe_curse = { state = "healed", effect = "hides scio affs and generally a bad time", cures = {}, assess = false, timer = createStopWatch() },
  aff_mystified = { state = "healed", effect = "stuck prone for a bit via voidgaze", cures = {}, assess = false, timer = createStopWatch() },

  --barbed arrow, ouch!
  aff_barbed_arrow = { state = "healed", effect = "10 stacks kills", cures = { balanceequilibriumtake = "pull arrow from body" }, assess = false, timer = createStopWatch() },

  --Soulbound from elite mobs
  aff_soulbound = { state = "healed", effect = "You gotta run away a bit to cure it", cures = {}, assess = false, timer = createStopWatch() },
  aff_infernal_explosion = { state = "healed", effect = "You're going to EXPLODE", cures = {}, assess = false, timer = createStopWatch() },


  aff_hopelessness = { state = "healed", effect = "writhe and tumble stopping", cures = { herb = "eucrasia" }, assess = false, timer = createStopWatch() },


  --bulk adding missing affs from afflict list
  aff_ashen_feet = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_backbreak = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_battlelust = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_blackstar = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_bowelgore = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_burden = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_city_hatred = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_dread = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_etherflux = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_hobbled = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_internal_disarray = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_lightheart = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_manabarbs = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_mindclamped = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_misfortune = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_possessed = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_spirit_tendril = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_staggered = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_symbol_marked = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_thunderbrand = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_excess_melancholic = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_trickery = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_typhonpoison = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_vacuity = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_varach_rot = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_was_tricked = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_pheromones = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_causality = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_fog_snared = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_remorse = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_contrition = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_fragments = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_immobility = { state = "healed", effect = "Can't move", cures = {}, assess = false, timer = createStopWatch() },
  aff_timewarped = { state = "healed", effect = "", cures = {}, assess = false, timer = createStopWatch() },
  aff_inaccuracy = { state = "healed", effect = "Reduced accuracy", cures = {}, assess = false, timer = createStopWatch() },


  aff_mindfog = { state = "healed", effect = "Can't cure mentals", cures = { salve = "caloric to head" }, assess = false, timer = createStopWatch() },
  aff_phosphenes = { state = "healed", effect = "Head trauma knocks eq", cures = { salve = "soothing to head" }, assess = false, timer = createStopWatch() },

}
