name: Release

on:
  push:
    branches:
      - main # Trigger on every push to main

permissions:
  contents: write # Needed to create the release
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Build Project
        run: nix build --out-link result

      - name: Archive Build Artifacts
        run: |
          mkdir -p artifacts
          cp -r result/* artifacts/
          tar -czf release.tar.gz -C artifacts .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: release.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: release.tar.gz
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
